### ISSUE TITLE
Add an 'alternating' layout mode

### ISSUE THREAD

**Issue by Lilith-In-Starlight** [glzr-io/glazewm#121]
The idea is to make it so that the behavior you get when alternating between horizontal and vertical layout mode before opening a window is done automatically, and you can move windows without destroying the structure that this creates. I think this would be A really good way to distribute the space that the windows take up on screen.

**Comment by lars-berger** [comment]
Similar to #102 

IMO what could be interesting is having some way of changing where new windows will be inserted. 

One possible implementation is having a property `default_insertion_algorithm: <i3 | alternating>`, and then being able to change the insertion algorithm on the fly via keybinding commands, eg. `insertion algorithm <i3 | alternating>`.

Are there any WM's that take a sort of hybrid approach to i3 and layout-based WM's like bspwm? Will leave this open for brainstorming & discussion.

**Comment by jervw** [comment]
I've been using this python [script ](https://github.com/olemartinorg/i3-alternating-layout)to alternate between horizontal and vertical windows on i3wm.

Maybe something like this could be implemented?

**Comment by Lilith-In-Starlight** [comment]
if we're gonna do a command for changing where new windows are put, it woudl also be useful to be able to refresh all windows so that they are set up in the way the current algorithm does it

so i could bind some key to change the insertion algorithm to alternating, and then press some other key so my windows are changed so that they align with that algorithm. or, bind both to the same key

this could disrupt with the thing you've been doing with the config files, which is having every possible config setting have a default key

**Comment by maphew** [comment]
Related, perhaps better as new feature request, is: how does or can a user know what the current insertion mode is?

**Comment by b1scu1t** [comment]
@maphew I'm thinking a new bar-component or expanding the existing 'tiling direction' component.

**Comment by anodynos** [comment]
In my first attempt, i tried to use `layout horizontal` to rearrange my 4 windows into a grid, instead of the 4 vertical bars (the default). 
It does nothing, I think I'm missing something or is it a bug?

**Comment by cigh033** [comment]
as per release 2.0.1 I tried my luck with a python script which alternates between the tiling directions after a new container is spawned with sizePercentage equal or lower than 0.5
![Animation](https://github.com/glazerdesktop/GlazeWM/assets/17072527/12e20f9f-c06e-4af9-b385-3753df76c9dd)

if you are interested, you can check it out here: https://github.com/cigh033/GlazeWM-autotiling-python/blob/main/main.py

Don't know if it works on every setup, with my monitor and laptop it works perfectly fine. Please handle it as a reference. I suck at coding.

**Comment by lars-berger** [comment]
Closing in favor of #678
