### ISSUE TITLE
issue with win combination keys?

### ISSUE THREAD

**Issue by rainsia** [glzr-io/glazewm#158]
GlazeWM is the best twm on Windows. I use it daily.

Howevery, I encounter a problem on Windows 10. 

When I use some [win] combination keys, for example, [LWin + R] or [LWin+=], if GlazeWM (version 1.8.1) is running, the start menu will show up.

For example, when I pressed [Win + R], the "Run dialog" did show up, but subsequently, the windows start menu will also show up.

I tried several key combinations, I guess the key combinations which start a floating dialog should also trigger the start menu.

**Comment by ParasiteDelta** [comment]
Can confirm, it's a bit weird how triggers the start menu for these commands. Unfortunately, I haven't found a solution other than to map the commands I'm most likely to use to keybinds in GWM. Of course, I wonder if you could just create a keybind in GWM to open the Run prompt...

**Comment by kavishkagihan** [comment]
I faced the exact same issue. I was able to get it somewhat under control by disabling the default windows shortcuts (because I don't use those that often, I mapped what I use i.e `Win+e` in my glaze config) so that I can map them to whatever I want.

```
  - command: "exec explorer"
    binding: "LWin+E"
```

But I wasn't able to solve the issue where the windows search menu popps up whenever I switch workspaces with `Win+<num>`. But theoretically, this is resolvable if replace the windows explorer itself with a custom shell by editing the registry key `WinLogon` as I presume.

**Comment by kavishkagihan** [comment]
Finally I was able to fix [this issue](https://github.com/lars-berger/GlazeWM/issues/158#issuecomment-1419505027) the  [this](https://superuser.com/a/1767509/1510161) AutoHotKey script

One thing to note here is that when switching workspaces you won't be able to switch 2 or more workspaces in a row while holding the Win key. You will have to press `Win+1` or `Win+2` etc from the beginning every time

**Comment by chalist** [comment]
your answer does not work for me! Start menu display every other switching!

So I used [Windows PowerToys](https://learn.microsoft.com/en-gb/windows/powertoys/keyboard-manager#keys-that-cannot-be-remapped) Keyboard Manager (thanks to [Rasmus's answer](https://superuser.com/a/1812167/143111)) to remap LWin to Alt; everything is fine now.

Also, I need the Win key, so remap right alt to the win key for emergency use cases :))

sounds stupid, but works fine!

**Comment by richcarl** [comment]
Really wanted to use Glaze, but I'm also a heavy Emacs user and need the Alt key for that, so I wanted to use LWin for Glaze. Tried every variant of AutoHotKey scripts that I could find, but none of them could prevent the Start menu from popping up constantly.

**Comment by lars-berger** [comment]
Fixed in v3 👍 [Latest release](https://github.com/glzr-io/glazewm/releases)

**Comment by richcarl** [comment]
Tried in 3.1.1, but the behaviour persists, e.g. the following:
```
- commands: ['focus --next-workspace']
    bindings: ['LWin+.']
```
does switch to the next workspace, but the Windows Search menu also pops up.

**Comment by lars-berger** [comment]
> Tried in 3.1.1, but the behaviour persists, e.g. the following:
> 
> ```
> - commands: ['focus --next-workspace']
>     bindings: ['LWin+.']
> ```
> 
> does switch to the next workspace, but the Windows Search menu also pops up.

This a related but different issue. There was a bug in v2 where any time you pressed a win combination key (eg `lwin+r`) it would open the start menu. This happened with the default keybindings without using `lwin` in bindings. Fix is in progress for the problem you mentioned you though, will be in the next release shortly

**Comment by kola-web** [comment]
> > Tried in 3.1.1, but the behaviour persists, e.g. the following:
> > ```
> > - commands: ['focus --next-workspace']
> >     bindings: ['LWin+.']
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > does switch to the next workspace, but the Windows Search menu also pops up.
> 
> This a related but different issue. There was a bug in v2 where any time you pressed a win combination key (eg `lwin+r`) it would open the start menu. This happened with the default keybindings without using `lwin` in bindings. Fix is in progress for the problem you mentioned you though, will be in the next release shortly

Still pure on this issue in v3.8.1
