### ISSUE TITLE
Expose current workspace

### ISSUE THREAD

**Issue by DakshG07** [glzr-io/glazewm#177]
Hey there, I'm really liking what I'm seeing. I was just wondering if you would be able to expose the current workspace number via a CLI interface? I want to connect this another program of mine and realized there's currently no way of doing it.

Thanks!

**Comment by notblam** [comment]
See my response in #232

**Comment by lars-berger** [comment]
Currently focused workspace is available via ipc + cli now 👍 `glazewm.exe query workspaces` will give an array of workspaces, and the currently focused one will have `hasFocus: true`
