### ISSUE TITLE
[Feature Request] Switch if workspace is empty

### ISSUE THREAD

**Issue by afermar** [glzr-io/glazewm#232]
If the current workspace is empty, move to the first previous non empty workspace. 
It could be implemented as an option for the user. 
For reference, there is a [script](https://github.com/giuseppe-dandrea/i3-switch-if-workspace-empty) that enables this behaviour in i3.

**Comment by notblam** [comment]
Similar to the i3 approach, maybe this is best implemented as a user script within GWM.  Currently we don't support IPC or CLI, but eventually we'd like to support a deeper customizations like this.  There has been recent work on this as well.  If anyone has done IPC work in the past and wants to contribute to the discussion, lots of talk around this has gone on within our discord.

**Comment by lars-berger** [comment]
IPC and CLI support has been added that would allow this to scripted now 👍
