### ISSUE TITLE
Dynamic Text Component

### ISSUE THREAD

**Issue by BashkaMen** [glzr-io/glazewm#251]
i want to be able to execute a script to get dynamic text
for example, display information about CPU, RAM, Bitcoin Price, another internet or local data
can i help with this?

**Comment by BashkaMen** [comment]
ideally i would like to be able to create such a bar
![image](https://user-images.githubusercontent.com/18517682/218519433-e12a2876-7dd0-4a7d-9860-eeb8ab2889f5.png)

**Comment by lars-berger** [comment]
Good idea 👍 This sounds like the equivalent of [polybar's script module](https://github.com/polybar/polybar/wiki/Module:-script). The way their component works is the user specifies a shell script to run in their config (eg `get-cpu-usage.sh`) and whatever that script outputs will be shown as text in the bar

Feel free to take a stab at making a PR for this if you want to. If you have any questions or need help with the codebase, we've got a [discord channel here](https://discord.gg/ud6z3qjRvM)

**Comment by BashkaMen** [comment]
i forked your repo and add new component
i use fsi scripting, because it easy to write for dotnet dev
https://github.com/lars-berger/GlazeWM/pull/252/files

**Comment by BashkaMen** [comment]
![изображение](https://user-images.githubusercontent.com/18517682/218580898-c840a95c-c2bb-44fc-8be6-abae718db3ce.png)

**Comment by lars-berger** [comment]
I'm closing feature requests and bugs about the built-in bar since it's now been swapped out for [Zebar](https://github.com/glzr-io/zebar). If Zebar doesn't fix what you need, a new issue for it can be opened over [here](https://github.com/glzr-io/zebar/issues)
