### ISSUE TITLE
updating keyboard image with the new commands

### ISSUE THREAD

**Issue by azinsharaf** [glzr-io/glazewm#286]
can these great keybindings be mentioned on the keyboard image?

```
  # Focus the workspace that last had focus.
  - command: "focus workspace recent"
    binding: "Alt+Y"

  # Focus the next/previous workspace defined in `workspaces` config.
  - command: "focus workspace next"
    binding: "Alt+T"
  - command: "focus workspace prev"
    binding: "Alt+Shift+T
``` 
    
![194635035-152ed4a6-e5a1-4878-8863-f62391e7d703](https://user-images.githubusercontent.com/10101468/227017971-0437f482-a995-4cf3-b62b-9d319450fd65.png)

**Comment by lars-berger** [comment]
Default keybinding image in readme is now up to date 👍
