### ISSUE TITLE
[question] Persistent top bar?

### ISSUE THREAD

**Issue by ctrlBIRDdelete** [glzr-io/glazewm#291]
Hi! I wasn't able to find the answer to my question in the documentation, but been wondering if it's possible to make the top bar act like the default windows task bar.

As of now, maximizing the window covers up the top bar. Since I need access to the clock pretty much all time at work I'd love to make it persistent so the single maximized window could only fill the space below the bar without gaps.

Is there a way to achieve this result somehow?

**Comment by lars-berger** [comment]
I'm closing feature requests and bugs about the built-in bar since it's now been swapped out for [Zebar](https://github.com/glzr-io/zebar). If Zebar doesn't fix what you need, a new issue for it can be opened over [here](https://github.com/glzr-io/zebar/issues)
