### ISSUE TITLE
Feature Request: display mode hide mode

### ISSUE THREAD

**Issue by Petar0000** [glzr-io/glazewm#295]
I think this feature would help maximize screen space usage:

Basically it would be like "display mode: hide mode" for i3, where the bar is only displayed while pressing some keybinding you can define in the config.

https://i3wm.org/docs/userguide.html#_display_mode

In terms of implementation: In order to avoid having to resize windows because of the bar appearing when toggled, maybe the bar could be rendered on top of all windows by default?

**Comment by Cornelius-Figgle** [comment]
would also like this, or maybe a more generic way to modify configs via a keybind (setting the bar height to 0px removes it currently, however a keybind to toggle `enabled` would be nice as well)

**Comment by xslendix** [comment]
same same

**Comment by lars-berger** [comment]
I'm closing feature requests and bugs about the built-in bar since it's now been swapped out for [Zebar](https://github.com/glzr-io/zebar). If Zebar doesn't fix what you need, a new issue for it can be opened over [here](https://github.com/glzr-io/zebar/issues)
