### ISSUE TITLE
Feature Request: option to use "cloak" for hiding windows

### ISSUE THREAD

**Issue by chrisfls** [glzr-io/glazewm#300]
[Cloak](https://devblogs.microsoft.com/oldnewthing/20200302-00/?p=103507) is used by the native virtual desktops to hide the windows.

Adding an option to use it instead of hiding the windows would:

1. allow alt+tabbing across workspaces (which could harmonize well with `toggle_workspace_on_refocus`)
2. reduce the impact of [crashes](https://github.com/lars-berger/GlazeWM/issues/293)

komorebi added `cloak` [with this commit](https://github.com/LGUG2Z/komorebi/commit/80c98596dd2cb4e28666e49c753ffc7e5137e09e)

**Comment by lars-berger** [comment]
Closing in favor of #671
