### ISSUE TITLE
How to bring up a minimized window?

### ISSUE THREAD

**Issue by crhf** [glzr-io/glazewm#327]
as the title

**Comment by exic** [comment]
I'm using Alt+Tab right now but if there's a better way I'd be happy to learn about it.

**Comment by notblam** [comment]
> I'm using Alt+Tab right now but if there's a better way I'd be happy to learn about it.

I've had the same thoughts.  Not sure what a good workflow would be.  I personally use workspaces in a way where most the time instead of minimizing something I put it on a different workspace.  I've wondered if there is a better way.

**Comment by marko-z** [comment]
Perhaps "unminimizing" all minimized windows in the given workspace with a single hotkey

**Comment by crhf** [comment]
Now I don't minimize windows. Most of the time I keep a single window in each workspace. If I have to keep multiple windows in the same workspace, I simply maximize the one I'm focusing on.

**Comment by lars-berger** [comment]
Closing this one out

Having an `unminimize-all` or `restore-all` command (perhaps have a flag for whether to restore all workspaces or just the current workspace) could be useful - if you still have a need for this, we could have a separate issue for this @marko-z?
