### ISSUE TITLE
system tray isn't showing all icons

### ISSUE THREAD

**Issue by calendulish** [glzr-io/glazewm#331]
I noticed that when activating the system tray in GlazeWM, some tray icons do not appear. This also prevent the icons to appear on the windows taskbar, so I need to disable the component and restart the programs to these icons appear.

**Comment by aaronedev** [comment]
> From my tests, when running GlazeWM as admin, it only shows tray icons of programs also running as admin. When Glaze is not running as admin, all icons are visible (also those running as admin).

yea that is correct - for me it behaves the same but whenever i open the terminal it wont focus it kinda floats and fucks up the alignment of the windows. Anyone experiences the same and does know how to fix it?

**Comment by zvbt** [comment]
> > From my tests, when running GlazeWM as admin, it only shows tray icons of programs also running as admin. When Glaze is not running as admin, all icons are visible (also those running as admin).
> 
> yea that is correct - for me it behaves the same but whenever i open the terminal it wont focus it kinda floats and fucks up the alignment of the windows. Anyone experiences the same and does know how to fix it?

i had the same issue its when you open an app in admin for my terminal i used this in my config

```
- command: "set floating"
    match_process_name: "alacritty"
```

**Comment by lars-berger** [comment]
I'm closing feature requests and bugs about the built-in bar since it's now been swapped out for [Zebar](https://github.com/glzr-io/zebar). If Zebar doesn't fix what you need, a new issue for it can be opened over [here](https://github.com/glzr-io/zebar/issues)
