### ISSUE TITLE
bar enable: false shows black bar and gaps outer_gap: more than one value doesn’t work 

### ISSUE THREAD

**Issue by tak2hu** [glzr-io/glazewm#347]
GlazeWM x64 1.11.1, Windows 11 2H22 downloaded using winget (pain bcuz appdata/local/microsoft/winget/packages is not in path)

When the config file does not have bar (after launching glazewm to generate default config and then commenting out the bar section), it shows a black bar on top.

Then I read the readme again and there’s enabled: false but it doesn’t work. But if I add height: 0px below enabled, it works. 

Would be nice to disable bar (includes black bar) when there’s no bar or bar enabled: false in config.

Also

gaps outer_gap: “5 0” doesn’t work nor “20px 0 20px 0”

When launching with that config, an error of Unhandled exception: Failed to parse user config. invalid value at property: ‘$.gaps.outer_gap’

**Comment by lars-berger** [comment]
I'm closing feature requests and bugs about the built-in bar since it's now been swapped out for [Zebar](https://github.com/glzr-io/zebar). If Zebar doesn't fix what you need, a new issue for it can be opened over [here](https://github.com/glzr-io/zebar/issues)
