### ISSUE TITLE
feature request: Move focused window to next/previous workspace

### ISSUE THREAD

**Issue by dipta10** [glzr-io/glazewm#352]
I think it would be great if we could move the focused window to the next/previous workspace with a key bind.
For example something like
```yaml
  - commands: ["move to workspace next", "focus workspace next"]
    bindings: ["RMenu+Shift+Right"]
```

**Comment by DreamMaoMao** [comment]
https://github.com/glzr-io/glazewm/pull/783

it has been supported in this pr
