### ISSUE TITLE
feature req: make a glazeCtl

### ISSUE THREAD

**Issue by jadedFella** [glzr-io/glazewm#361]
- make something like glazeCtl or something that helps to view classes of the program or titles in runtime
- It can help show the monitor ids connected etc too for easy viewing
- just a program that exposes debug info through a cli tool, or just make a lib that has debug messages (ik you log them already but still)

I'm up to do a pr btw if you would like this to be a thing.

**Comment by lars-berger** [comment]
That actually sounds like a great idea 🙌

A CLI + IPC server was added very recently (it's not part of an official release yet). As part of it, there is actually a way to get info about monitors and _managed_ windows now via `./glazewm.exe monitors` and `./glazewm.exe windows`. However, it spits out pretty unreadable JSON.

I think it'd make a lot of sense to add something like you're suggesting with an easy to read way to see all monitors/windows. A question that pops up a lot on the discord is how to target a particular window with window rules, and there isn't really a good way to do it currently. 

Quick idea for potential api:

```shell
glazewm debug --monitors # lists out all monitors in a nicely formatted way
glazewm debug --visible-windows # lists out all windows (managed + unmanaged) in a nicely formatted way
```

Feel free to take a stab at this 👍 If you want some inspo on how to approach it, take a look at `GetMonitorsMessage` (new CLI commands are exposed via `Program.cs` and then implemented in `IpcMessageHandler.cs`). `WindowService.cs` contains a lot of helpful utilities like getting titles, class names, visibility, etc of a window. There's also a #contributing channel on discord if you wanna ask questions

**Comment by jadedFella** [comment]
nice, where's the discord server link though? couldn't find it in the readme or on your profile.

**Comment by lars-berger** [comment]
> nice, where's the discord server link though? couldn't find it in the readme or on your profile.

https://discord.gg/ud6z3qjRvM

**Comment by lars-berger** [comment]
CLI commands can be used to print window titles, class names, and process names (i.e. `glazewm.exe query windows`), as well as monitor info (i.e. `glazewm.exe query monitors`). We could perhaps add a flag to pretty-print the output to make it more user-friendly but that should be its own issue
