### ISSUE TITLE
GlazeWM crashes if Weather component fails to fetch info.

### ISSUE THREAD

**Issue by b1scu1t** [glzr-io/glazewm#363]
If the weather component is enabled and GlazeWM is (re)started without an Internet connection, it will crash immediately.
GlazeWM was built from source, and the Weather component's config was copied from the Readme.md.

**Comment by hansoolow** [comment]
Hi. 
@lars-berger How should the missing network connection be handled? Should an error be thrown, or should the component maybe not be visible, if no internet connection is available?

I think this issue is really good as a first issue and I would be happy to help :)

**Comment by lars-berger** [comment]
I'm closing feature requests and bugs about the built-in bar since it's now been swapped out for [Zebar](https://github.com/glzr-io/zebar). If Zebar doesn't fix what you need, a new issue for it can be opened over [here](https://github.com/glzr-io/zebar/issues)
