### ISSUE TITLE
windows manipulated with altdrag or altsnap don't re-tile

### ISSUE THREAD

**Issue by airtonix** [glzr-io/glazewm#367]
title is enough: 

- have altsnap or altdrag installed
- have glaze running.
- resize a window with altdrag or altsnap
- witness as the window does not cause all other tiled windows to relayout.

**Comment by HolbyFPV** [comment]
Rather than solving compatibility, we should re-create the parts of altdrag that make sense with GWM.  Having multiple programs competing to manage a window is likely to cause problems.  

If anyone wanted to work on this I'd be happy to see a PR.

**Comment by DreamMaoMao** [comment]
This issue doesn't seem to be with me, I'm using altsnap 1.63

**Comment by DreamMaoMao** [comment]
https://github.com/RamonUnch/AltSnap/pull/564

the pr fix the problem.
