### ISSUE TITLE
GeForce Experience overlay shows with each focus changes.

### ISSUE THREAD

**Issue by aardvark** [glzr-io/glazewm#40]
Raised for 1.2.0 version.

I have GeForce Experience overlay enabled. 
When I am changing focus from one application to another (Alt + hjkl) this overlay is "automatically" brought to the front:
![image](https://user-images.githubusercontent.com/159930/163683817-abc0bd35-ca6e-4d40-80ab-d698d66f3405.png)

I have tried to remove managing of this app window through window_rules section:
```
window_rules:
  - command: "ignore"
    match_process_name: "nvcontainer"
```

But so far I had no luck. 

If you have any advice on how to debug this behavior I can try to spin-up local development setup and dig a little more information.

**Comment by lars-berger** [comment]
What keybinding is the overlay set to be opened with? The overlay might be listening on one of the same keybinding as GlazeWM has set. 

![image](https://user-images.githubusercontent.com/34844898/163688850-8da40ede-974b-4bb3-9958-12c71e00a77a.png)

Also, should mention that when an app is ignored in the window rules, it just means the WM won't try to move it around and that focus can't be set to it via focus commands (eg. `"focus left"`) .

**Comment by aardvark** [comment]
Rechecked shortcut. Currently shortcut to open/close is set to the "ctrl+alt+shift+z" and all other shortcuts are disabled. 

Overlay get "focus" every time I try to change focus using "hjkl" and every time I add or remove new window to the layout. Just using mouse to open/close/minimize windows produces same effect.

Looks like there is conflict with "Broadcast LIVE" option in GeForce Experience. 

![image](https://user-images.githubusercontent.com/159930/163711064-9367c34f-de5a-48db-bf4c-564a59a000f3.png)

As soon as I disable this option I stop getting overlay pop-ups on focus changes. 

Not sure yet how this is linked with window focus functionality.

**Comment by lars-berger** [comment]
Unable to reproduce this in the latest version 👍
