### ISSUE TITLE
GlazeWM Questions Please...

### ISSUE THREAD

**Issue by ComputerCulture** [glzr-io/glazewm#401]
Hello,

Really enjoying this software and thank you. If i may ask some questions please.

1. Is this possible to have as an option for the windows tiling type as, "Master and Stack" 
Example, as in xmonad tiling window manager on Linux.

![master stack](https://github.com/glazerdesktop/GlazeWM/assets/133943765/fc11fb59-e41f-4cbd-8207-6ccbc62cc131)

2. On a two monitor setup, is it possible to only have the tiling on the first monitor only, and ignore the second monitor always?

3. I think this has been asked but allow tiling windows to be moved via click and drag.

Thank you in advanced.

Best regards 
CC

**Comment by HolbyFPV** [comment]
1. #301 
2. Not at the moment.
3. #367

**Comment by ComputerCulture** [comment]
Hi HolbyFPV
Thank you for your reply and help with question 3.
Do you know any time line when  question 1 
https://github.com/glazerdesktop/GlazeWM/issues/301 
might be be implemented into GlazeWM?
Thanks again
Best regards
CC

**Comment by HolbyFPV** [comment]
No one is actively working on this.  We would welcome a PR for this if anyone reading is interested in giving it a try.
