### ISSUE TITLE
[Feature request] Switching workspace automatically when clicking the app icon in the system taskbar instead of creating a new instance

### ISSUE THREAD

**Issue by oulongwen** [glzr-io/glazewm#416]
Hello. First of all, thank you for the great WM that delivers the best user experience among all the WM for Windows I have tried.

I have noticed that the Windows taskbar (not the bar generated by GlazeWM) only shows the icons of the apps that are opened in the current workspace. Therefore, if I have a browser window open in Workspace 1, and I am in Workspace 2, I am not able to switch back to the browser window by clicking the app icon in the taskbar. If the browser icon is pinned to the taskbar, clicking it while in Workspace 2 will create another instance of the app in Workspace 2. I don't think this is the expected behavior for most users. Would it be possible to show all the opened apps in the system taskbar and switch to the corresponding workspace that includes the target app when users click on the icon in the system bar?

**Comment by rpop0** [comment]
Yeah I agree this is a needed feature. It is very annoying that only the icons of the active workspace apps are shown in the taskbar.

It would be great if the taskbar always showed all the active windows, and maximizing one would bring into focus the workspace containing it.
