### ISSUE TITLE
Can't drag tabs in Chromium based browsers

### ISSUE THREAD

**Issue by jnzd** [glzr-io/glazewm#43]
In Chromium based browsers I can't drag tabs between browser windows or into a new window. As soon as I drag a tab and leave the space designated for tabs in the window, i.e. dragging the tab out of the window, it just jumps back to where it was. For an instant the outline of a new tiled window appears, before disappearing again.

This happens in Google Chrome, Chromium, Microsoft Edge (Chromium), Brave, and presumably any other Chromium based browser.

Firefox doesn't have this issue and lets me drag a tab out of the current window to create a new window. It also allows me to drag tabs between existing Firefox windows.

I'm running Windows 11 Home, version 21H2, build 22000.613
![2022-04-17-17-01-44_Trim](https://user-images.githubusercontent.com/26679346/163725710-b0e3c28d-8da7-4516-9e72-4ee3729def06.gif)

**Comment by jnzd** [comment]
After restarting the window manager again the issue is now completely gone. I will therefore close this issue.

**Comment by lars-berger** [comment]
Actually running into the same issue on Chromium-based browsers. Did you make any changes to the window rules in the user config? Might have to re-open this.

**Comment by jnzd** [comment]
No, I did not make any changes to the config. The issue is now back for me again. I did not restart the window manager, but I did lock Windows since it worked. So I have no idea why the issue was gone and why it came back. I will see if I can get it to work again and whether there is a consistent way to make it happen.

I'm re-opening this issue.

**Comment by JPhusion** [comment]
I have the same issue, some notes: 
- I restarted the window manager and the issue still persists.
- I was able to make it work by clicking on the tab, dragging down and releasing it very quickly, although this is very difficult to replicate. I was able to do it twice in about 20 tries.
- Workaround: right click the tab and open it in a new window/move to a new window.

**Comment by crimist** [comment]
I've been able to reproduce this and find the problem area 🎉

![image](https://user-images.githubusercontent.com/20033376/172457633-3f74a6e5-b3f5-44bc-bf1f-b686328757c2.png)

In the image above dragging the tab **outside** the red box causes it to immediately return the it's existing window as demonstrated by the issues author. This means dragging it down, left, right, or up to Glaze's bar causes the issue.

However dragging the tab carefully **into** the red box which can be described as the space between the bar and the window does cause the tab to create a new window.

**Comment by b1scu1t** [comment]
The bug occurs on some Chromium-based browsers. Vivaldi, for example, doesn't have this issue.

**Comment by ShortArrow** [comment]
I use Chrome and [Thorium](https://thorium.rocks/) in Windows 10  Pro and 11 Pro, doesn't have this issue.

**Comment by DreamMaoMao** [comment]
This issue seems to have been removed from version 3.4
