### ISSUE TITLE
Can't get focused_workspace_border_width to work

### ISSUE THREAD

**Issue by jo-project** [glzr-io/glazewm#431]
I try to use focused_workspace_border_width but it doesn't work. How to solve it?

![GlazeWMs](https://github.com/glazerdesktop/GlazeWM/assets/122333339/7593433f-ebdd-4b9b-a4f9-dfe3e3e349cb)

**Comment by azinsharaf** [comment]
can you please share your beautiful config file? :) are you using a custom Windows theme?

**Comment by lars-berger** [comment]
I'm closing feature requests and bugs about the built-in bar since it's now been swapped out for [Zebar](https://github.com/glzr-io/zebar). If Zebar doesn't fix what you need, a new issue for it can be opened over [here](https://github.com/glzr-io/zebar/issues)
