### ISSUE TITLE
Numpad key bindings

### ISSUE THREAD

**Issue by michie1** [glzr-io/glazewm#434]
In the docs it's stated we can use the keys from https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.keys?view=windowsdesktop-5.0#fields
In this list there is no `KP_Home` (like in unix). It's `Home` and equals the one that's not on the numpad. (Same holds for the other keys.) On that link there is a note `This enumeration provides no way to test whether the CAPS LOCK or NUM LOCK keys are currently activated.` 

Is there another way to distinguish between them?

A workaround could be to configuring AutoHotKey Dash and calling commands via the CLI.

**Comment by lars-berger** [comment]
This is now possible via e.g. `alt+numpad1` - [full list of available keys](https://github.com/glzr-io/glazewm?tab=readme-ov-file#config-keybindings)
