### ISSUE TITLE
[Feature request] A floating command and rule that does not tile the window first, like set floating is doing now.

### ISSUE THREAD

**Issue by Video-Nomad** [glzr-io/glazewm#436]
Hi,

It would be great to be able to create a window rule that will launch the new app in floating mode by default, without first docking it and undocking.

An example of the issue I currently have with "set floating":
- I have two apps tiled side by side, widths are 30/70.
- I open a new app that has "set floating" in window_rules.
- The expected behavior is that the 30/70 width is maintained in the original tiles and a new window is simply created on top as floating.
- The actual behavior is that the new app is first docked, and then undocked, messing with the widths of the original tiles in the process.

Setting the tiling direction to vertical has no effect on this behavior.

As an additional note, "set floating" always centers the window[...]
<details>
<summary>[FIXED] with #476 on develop branch. Floating centering is now optional. </summary>

[...] but it would be better for some apps to have an option to use the original position. For example, when I use Autodesk Maya ("set floating" by default) all the in-app floating windows are always centered by GlazeWM, and you open and close those windows all the time when using the app. Setting those apps to "ignore" is not great either, since you can't set to ignore and tile some of those windows if you need to later, there's no ignore toggle.

Using regex title match works in this case, so I can set to ignore everything except for the main window that has "Autodesk MAYA":
```
- command: "ignore"
    match_process_name: "/maya/"
    match_title: "/^(?:(?!Autodesk MAYA).)*$/"
```
But it might not work with other similar apps.
</details>

Really enjoying the window manager, the best I've tried, that's for sure. Thank you!

**Comment by nahid6970** [comment]
same issue  have u found any solution

**Comment by lars-berger** [comment]
Fixed in v3 👍 [Latest release](https://github.com/glzr-io/glazewm/releases)
