### ISSUE TITLE
[feature request] setting the default status of system tray

### ISSUE THREAD

**Issue by azinsharaf** [glzr-io/glazewm#441]
is it possible to set the default status of system tray? (collapse or expand)
I prefer it to be collapsed by default.

**Comment by WiiPlayer2** [comment]
I'd be willing to implement it as I want this as well as long as it's accepted by the maintainers.

**Comment by AleGrz** [comment]
I will implement this to be configurable soon, but [https://github.com/AleGrz/GlazeWM/releases](here) is a quick fix (non configurable, hidden on startup).

**Comment by darianmorat** [comment]
I will also love to be able to toggle this option, always at the startup I need to collapse the option

**Comment by lars-berger** [comment]
I'm closing feature requests and bugs about the built-in bar since it's now been swapped out for [Zebar](https://github.com/glzr-io/zebar). If Zebar doesn't fix what you need, a new issue for it can be opened over [here](https://github.com/glzr-io/zebar/issues)
