### ISSUE TITLE
Case sensitivity in exec 

### ISSUE THREAD

**Issue by theKidOfArcrania** [glzr-io/glazewm#443]
Seems like `exec` command is inherently always case-insensitive (i.e. will be forced to be lowercased), [see code](https://github.com/glazerdesktop/GlazeWM/blob/454bc05cade0bc7eea4ffebd9af5c57dd87c85d3/GlazeWM.Domain/UserConfigs/CommandParsingService.cs#L48). Should this always be the case? What if (in my case) I want to specify some command that requires case sensitivity (for example the command `wt nt --profile Debian` gets quietly converted to `wt nt --profile debian` and then you would be left to wonder why windows terminal never pulls up the Debian profile instead of the default one)?

**Comment by lars-berger** [comment]
Fixed in v3 👍 [Latest release](https://github.com/glzr-io/glazewm/releases)
