### ISSUE TITLE
[bug] Crash "eats" windows?

### ISSUE THREAD

**Issue by melMass** [glzr-io/glazewm#448]
Hi,

I've been using glaze for a few weeks and I really enjoy it.
I just got my first crash with it (the whole glaze widgets where stuck, WM stuff weren't responding)

I ended its task as it didn't want to shut cleanly from the tray icon's exit button.

Upon closing, all the windows scattered in various workspaces are gone.

So I was wondering two things:

- Where do they actually went you think? Did they close or somehow became "unreachable" and like still there as ghost processes?
- Similar to this I was wondering before how muliwindow apps (scattered on multiple workspace) can be "merged" back into the same space/start bar icon?

**Comment by melMass** [comment]
Yep it seems they are 'ghost' process...
I just installed [merge windows](https://chromewebstore.google.com/detail/merge-windows/mmpokgfcmbkfdeibafoafkiijdbfblfg?pli=1) and it retrieved the browser windows that were gone from that crash

**Comment by b1scu1t** [comment]
Most likely you are running an older version of GlazeWM. As of version 2.0.0, all managed windows are restored when the main process dies.

https://github.com/glazerdesktop/GlazeWM/releases/tag/v2.0.0

**Comment by melMass** [comment]
Thanks, but I'm using the [2.0.3](https://github.com/ScoopInstaller/Extras/blob/master/bucket/glazewm.json) version from scoop so I don't think that's it.
I also had another similar one when "detaching" a tab from a browser window, that said tab disapeared and couldn't be retrieved from any space, I again use the `MergeWindows` chrome extension to retrieve them, just not sure how much it happens in other apps

**Comment by BobTB** [comment]
Happened to me today, all windows on different workspaces were gone. I used the[ GUIPropView](https://www.nirsoft.net/utils/gui_prop_view.html) from Nirsoft to get them back ("TopLevel - Display hidden windows") and them made them visible, but this was a pain.

**Comment by caiiiycuk** [comment]
Same for me on v2.1.1

**Comment by MoaidHathot** [comment]
I think the best approach is to persist the workspaces so that relaunching glaze will use the last session

**Comment by BobTB** [comment]
Was this fixed?

**Comment by MoaidHathot** [comment]
> Was this fixed?

Unfortunately, not yet. I think we can't expect a fix before the rewrite work is done.

**Comment by aaronedev** [comment]
yea it still happens to me as well but you can also use: https://www.nirsoft.net/utils/winlister.html to revive the lost windows

**Comment by MoaidHathot** [comment]
@BobTB, @aaronedev, do you have the error logs with the exceptions?

**Comment by lars-berger** [comment]
Restoring windows on exit has been overhauled in v3 - it should be a lot more stable now 👍
