### ISSUE TITLE
[Feature Request] `exec` bar component

### ISSUE THREAD

**Issue by btvoidx** [glzr-io/glazewm#450]
As of now, it is possible to pipe output from any program's stdout into a file and then open that file as a bar component. But doing so is cumbersome, and the program is completely independent from the wm, even though it's whole purpose is to provide data to the wm.

I propose an `exec` type component, which takes a command to run and shows the last line from its stdin. Line separator should be configurable, as well as the label. When the program stops, it should be restarted according to a configurable restart policy: never, always, or after some time.

This would greatly simplify creating custom components.

**Comment by aaronedev** [comment]
+1

**Comment by lars-berger** [comment]
I'm closing feature requests and bugs about the built-in bar since it's now been swapped out for [Zebar](https://github.com/glzr-io/zebar). If Zebar doesn't fix what you need, a new issue for it can be opened over [here](https://github.com/glzr-io/zebar/issues)
