### ISSUE TITLE
[Bug] GWM Rules Do Not Properly Target Elevated Processes

### ISSUE THREAD

**Issue by ParasiteDelta** [glzr-io/glazewm#451]
So, I've been doing a bit of testing, trying to get GWM to always ignore CMD run as Admin, and literally no rule works until you reload the GWM config with the elevated window open.

Things I've tried:
```
- command: "ignore"
  match_title: "<title>"
  
- command: "ignore"
  match_process_name: "cmd"
  match_title: "<title>"

For title:
"/Administrator/"
"/^.*Administrator.*$/"
"/.*Administrator.*/"
"/Administrator.*/"

And just for giggles:
"Administrator"
```

I bring this up since I've encountered a couple modern games that also run as elevated processes, following a similar mismanagement pattern, though this is a bit more expected since I push games to a different workspace rather than outright ignoring them.

Successfully ignored Admin CMD:
![Successfully Ignored Admin CMD](https://github.com/glazerdesktop/GlazeWM/assets/19669733/2445b19b-7bba-4e24-9c1c-367ca41e095e)

Fresh Admin CMD window before refreshing GWM config:
![image](https://github.com/glazerdesktop/GlazeWM/assets/19669733/0aa64789-f2ab-4112-bf48-a332dae66cf2)

Fresh Admin CMD window after refreshing GWM config:
![image](https://github.com/glazerdesktop/GlazeWM/assets/19669733/567faafb-e007-4424-8450-f6f17157ca7c)

I don't know why this is still a thing, but I'm beginning to wonder if there's some kind of weird pollution effect going on within GWM's temp files, as there were similar anomalous effects that purging helped with before.

**Comment by aaronedev** [comment]
+1 i wonder that too kind of annoying when using non + elevated windows

**Comment by lars-berger** [comment]
The application is now signed and `uiAccess` is enabled 🎉 Admin windows can finally be managed without running the WM as admin
