### ISSUE TITLE
Exec always opens CMD

### ISSUE THREAD

**Issue by alamb3142** [glzr-io/glazewm#452]
### Context 

I want to rebind Alt+Enter to open WezTerm as that's what I use in place of Windows Terminal. I have changed the command from "exec cmd" to "exec wezterm.exe".

### Expected Behaviour

WezTerm opens when typing Alt+Enter

### Actual Behaviour

A cmd window opens that then spawns the process for WezTerm. This creates two windows instead of just the WezTerm window. Because the cmd window owns the WezTerm process I can't close it without also closing WezTerm.

Here is the result of executing that key bind:
![image](https://github.com/glazerdesktop/GlazeWM/assets/127202207/9f88c262-32df-4405-bad5-1382b2e6ec14)

**Comment by Fuann-Kinoko** [comment]
you should launch `wezterm-gui.exe` instead of `wezterm.exe`

**Comment by Pagliacii** [comment]
Launching `wezterm-gui.exe` also has a blank cmd window.

**Comment by IsaacTay** [comment]
You may need to use the full path (eg. `exec 'C:/.../wezterm-gui.exe`), that was what worked for me.

**Comment by alamb3142** [comment]
Yeah this is working for me now with `exec %ProgramFiles%/WezTerm/weterm-gui.exe`. It would be nice to have more flexibility in opening programs, as other apps may not have a -gui variant that spawns a new process. 

I might look into that at some point, I think this issue can be closed as what I've just described sounds more like a feature request.

**Comment by data-miner00** [comment]
For the record, I am using v3.4.0 and I can just specify `wezterm-gui` in the `shell-exec`. This will not open a separate `cmd.exe` window.

```yml
- commands: ['shell-exec wezterm-gui']
  bindings: ['alt+enter']
```

However, this will launch a separate `cmd.exe` process.

```yml
- commands: ['shell-exec wezterm']
  bindings: ['alt+enter']
```
