### ISSUE TITLE
[Feature Request] Scrolling trough opened workspaces in glazebar

### ISSUE THREAD

**Issue by ricardovac** [glzr-io/glazewm#453]
### Current Behavior:
As of the latest version of Glazewm, users are unable to scroll through open workspaces directly from the bar. This limits the user experience, especially for those who frequently use multiple workspaces simultaneously.

### Expected Behavior:
I propose the implementation of a workspace scrolling feature in the bar. This feature would enable users to navigate through their open workspaces easily, providing a more efficient way to manage and switch between different desktop environments using the mouse just like i3wm.

**Comment by lars-berger** [comment]
I'm closing feature requests and bugs about the built-in bar since it's now been swapped out for [Zebar](https://github.com/glzr-io/zebar). If Zebar doesn't fix what you need, a new issue for it can be opened over [here](https://github.com/glzr-io/zebar/issues)
