### ISSUE TITLE
[Bug] WorkspaceComponent always has border, regardless of borderthickness attribute

### ISSUE THREAD

**Issue by jbawgs** [glzr-io/glazewm#454]
Installed this yesterday and spent a while trying to figure out why my workspace component borders were a thick blue:

![image](https://github.com/glazerdesktop/GlazeWM/assets/12999984/82e9bd56-e829-47cd-99df-122ddfac2195)

This is the config:

![image](https://github.com/glazerdesktop/GlazeWM/assets/12999984/bf951d12-9a46-4f3f-8fd9-3c643c5c56ce)

If we specify *_workspace_border_width there is no effect, though we can change the color:

![image](https://github.com/glazerdesktop/GlazeWM/assets/12999984/cfcf9a8b-4696-447a-97fa-13d20595feab)

![image](https://github.com/glazerdesktop/GlazeWM/assets/12999984/f7432e3e-7569-435e-aeca-3e8d40a9d637)

I tried "0", "0,0,0,0","0px","0px,0px,0px,0px","10"

I am not familiar with the intricacies of XAML/WPF but I cloned the repo and tried a few things.

Setting the thickness directly in WorkspacesCompnent.xaml similarly has no effect, same attempted value sets on all three states.

The only way I have found to affect the "BorderThickness" is to remove the "BorderBrush attribute from XAML and we get what appears to be a regular shadowed windows button but no border:

![image](https://github.com/glazerdesktop/GlazeWM/assets/12999984/094d7542-0d02-43c4-b980-c111f8efda60)

But, no configuration that I know how to set affects the "Borderthickness" attribute the way I assume it is intended.

**Comment by Lol-Lap** [comment]
The only way of fixing it rn #420. If you want the colored button portion to touch the top and bottom of the bar, you can adjust the margins to your liking using a negative value. So, margin: "-10px" to get a default look.

**Comment by Fuann-Kinoko** [comment]
it is a well-known bug if you're using a customized theme, `borderWidth` works fine but the blue border attached in pic is another thing. Possible related to #420

**Comment by lars-berger** [comment]
I'm closing feature requests and bugs about the built-in bar since it's now been swapped out for [Zebar](https://github.com/glzr-io/zebar). If Zebar doesn't fix what you need, a new issue for it can be opened over [here](https://github.com/glzr-io/zebar/issues)
