### ISSUE TITLE
packaging glaze wm as a Shell?

### ISSUE THREAD

**Issue by theSoberSobber** [glzr-io/glazewm#464]
A lot of people would love to use glaze wm as a shell instead on windows because of the explorer being incredibly annoying and buggy when some application does high frequency use of dwm apis. The good news is that it is possible since `Desktop Window Manager.exe` does not care about explorer.exe or need it! One could just modify a reg key and set glaze as shell since all it requires is a setting a shell key with the path to a PE executable, however there are issues, I've identified two and they both seem fixable - 

- UWP Apps don't work if explorer is killed, see [this](https://github.com/MishaProductions/CustomShell) for a workaround.
- Explorer hosts the wallpaper and hence it doesn't stay if explorer is killed (see blackbox shell on how to set a wallpaper without explorer)

This Shell/Husk if being made should ideally be something that spawns glaze/komorebi/workspacer like window managers and not something integrated with glaze fully, so one could maybe hotswap window managers.

Advantages of not having explorer - 
- Complete control of hotkeys
- no loss in app compatibility (is UWP patch is being implemented)

**Comment by lars-berger** [comment]
I'm sure a lot of people would be interested in this (myself included). A replacement shell is a huge endeavor though and imo should exist as a separate project to GlazeWM

Closing this but would be excited to see you get further with this idea🙏
