### ISSUE TITLE
[Feature Request] Border radius on the background color

### ISSUE THREAD

**Issue by zvbt** [glzr-io/glazewm#493]
I would like to propose a new feature that allows users to apply a border radius to the background color of a component in the bar.

**Comment by lars-berger** [comment]
I'm closing feature requests and bugs about the built-in bar since it's now been swapped out for [Zebar](https://github.com/glzr-io/zebar). If Zebar doesn't fix what you need, a new issue for it can be opened over [here](https://github.com/glzr-io/zebar/issues)
