### ISSUE TITLE
[bug] [release 2.1.0] In the latest release, when a window is maximized on dual monitor setup, focus left/right does not work

### ISSUE THREAD

**Issue by dipta10** [glzr-io/glazewm#495]
- When there is a window in full-screen mode (maximized) on one monitor, focus [left, right, up, down] does not work. 
- I think the expected behavior should be, when in fullscreen, focus right should focus window on the right monitor (if available) like i3wm.

To reproduce the issue
- in a dual monitor setup, maximize a window on the left monitor
- then click the focus right key bind to focus on a window on the right monitor, it should not work

**Comment by lars-berger** [comment]
This has been fixed now in v3 👍 [Latest release](https://github.com/glzr-io/glazewm/releases)
