### ISSUE TITLE
How to get some windows to stack vertically and some to stack horizontally?

### ISSUE THREAD

**Issue by kawaleo** [glzr-io/glazewm#497]
I noticed in the demonstration GIF how you are able to make certain windows vertically stacked and some horizontally stacked. After checking the images for the keymaps, I am unable to figure out how to do this. The closest I found was Alt+Shift+Down, but that just changes the stacking for all the windows.

I am running Windows 10.

**Comment by DaNubCoding** [comment]
Alt-v. There is an image containing all heybinds in the main readme.
