### ISSUE TITLE
[Bug] Resized windows revert back to their original size

### ISSUE THREAD

**Issue by Narco-AI** [glzr-io/glazewm#506]
GlazeWm version : 2.1.0

Trigger: Minimizing the maximized window / Window when reverted back to normal from fullscreen. | State: Tiled 
Action/Issue: Reverts the resized window to its original state. 
*Tested in windows 10/11 scratch VM's*

Visual example:

https://github.com/glzr-io/glazewm/assets/75385245/747dec69-8a6f-4c51-ad8c-75a51b909b5e
https://github.com/glzr-io/glazewm/assets/75385245/17c449bf-c0c6-4e73-bffe-acdc5eacb617

Previous glaze versions were working fine, resized windows were sustained but the fullscreen persistance added in the new version somewhat introduces this issue.

**Comment by JohannesPertl** [comment]
Any updates on this one? That's the only issue I find extremely annyoing

**Comment by lars-berger** [comment]
From a technical standpoint, can be fixed by storing the tiling size and number of tiling siblings in `insertion_target` of `NonTilingWindow`'s. If the number of tiling siblings changed on re-insert, adjust the tiling size accordingly.

**Comment by sibouras** [comment]
onyone has a workaround for this? a manual patch until a better solution is found? its literally unusable for me without this fixed :(
