### ISSUE TITLE
Tiling direction doesn't show icon until keybind is pressed

### ISSUE THREAD

**Issue by cdurbin909** [glzr-io/glazewm#513]
## Issue
After each config reload, tiling direction icon is blank until the keybind to toggle is pressed.

#### Expected behavior
![image](https://github.com/glzr-io/glazewm/assets/74153584/1cbd6e83-2608-4470-b1bf-2bab36fbc0c0)

#### Actual Behavior
![image](https://github.com/glzr-io/glazewm/assets/74153584/bab8c7b5-3b65-4999-8adb-ad579da7917f)

**Comment by BobTB** [comment]
Yes, same here. It shows after some window is selected, but is blank before.

**Comment by aaronedev** [comment]
+1

**Comment by lars-berger** [comment]
I'm closing feature requests and bugs about the built-in bar since it's now been swapped out for [Zebar](https://github.com/glzr-io/zebar). If Zebar doesn't fix what you need, a new issue for it can be opened over [here](https://github.com/glzr-io/zebar/issues)
