### ISSUE TITLE
Keep statusbar when Maximized

### ISSUE THREAD

**Issue by darianmorat** [glzr-io/glazewm#515]
Is there any way to keep the statusbar visible when maximized? I mean, I want to be able to see the statusbar and have full screen apps, but now u have two options: 

- Gaps with status bar
- Full screen without status bar

If u remove the gaps, U still have the color rounded borders. So that is not a solution, and thanks, amazing software

**Comment by azinsharaf** [comment]
can you explain `Gaps with status bar`? how do you set the gap with the status bar so maximizing a windows doesn't cover the bar?

**Comment by azinsharaf** [comment]
i mean even if you set gaps with status bar, the maximized window will cover the bar, correct?

**Comment by darianmorat** [comment]
What I what to do, you can do it with the current options. BUT, the default rounded corners that windows has is the problem, cause if I remove the gaps, I can have my window using the whole space and I can see the status bar, BUT you can also see the corners... 
In windows instead, when you maximize a window you can still see the status bar (taskbar), OR you can hide it, I think this is more clear now. 

- Or maximize window option that is gonna keep the status bar (so It needs to adjust the window and not just make the status bar to be on top)
- Or removing the rounded corners (which is not optimal, cause of the bugs it carries)

**Comment by nahid6970** [comment]
> * Or removing the rounded corners (which is not optimal, cause of the bugs it carries)
what kind fo bugs do u face removing rounded corner ? i removed rounded corner using Win11DisableOrRestoreRoundedCorners
and i dont have any problems

**Comment by lars-berger** [comment]
I'm closing feature requests and bugs about the built-in bar since it's now been swapped out for [Zebar](https://github.com/glzr-io/zebar). If Zebar doesn't fix what you need, a new issue for it can be opened over [here](https://github.com/glzr-io/zebar/issues)
