### ISSUE TITLE
pre-defined layout templates?

### ISSUE THREAD

**Issue by NireBryce** [glzr-io/glazewm#523]
I scoured the docs here and searched as much as I could through the issues and didn't find anything on this.

I know it would take a lot to impliment, but I was wondering if there is already undocumented functionality for pre-defining a window layout such that I can have an easier time slotting my apps into it?

my current portrait setup looks like
```
    ._____.
    |_____|
    |_____|
    |  |  |
    |__|__|
    |__|__|
```

and it's a huge pain to re-place everything on every boot/crash.

**Comment by lars-berger** [comment]
Closing in favor of #678
