### ISSUE TITLE
Prevent Unexpected Exits Before Applying Bad New Config 

### ISSUE THREAD

**Issue by BobTB** [glzr-io/glazewm#535]
**Issue Description**

When modifying the configuration file for GlazeWM, I've encountered a significant usability issue that affects workflow efficiency. If there happens to be a typo or any form of syntax error in the configuration file, GlazeWM immediately attempts to apply these changes and, upon encountering the error, exits. This behavior not only disrupts the current session but also requires manually reorganizing and tiling all windows again, which is time-consuming and frustrating.

**Expected Behavior**
Ideally, GlazeWM should validate the configuration file for errors before attempting to apply any changes.

**Steps to Reproduce**
Introduce a typo or syntax error in the GlazeWM configuration file.
Attempt to apply or reload the configuration.
Observe that GlazeWM exits and disrupts the current session.

**Comment by lars-berger** [comment]
This has been fixed now in v3 👍 No more crashes on bad config reloads
