### ISSUE TITLE
Why did the system tray and network disappear on the Windows 11 taskbar after installing GlazeWM? Is there any way to restore it?

### ISSUE THREAD

**Issue by 2795895564** [glzr-io/glazewm#539]
After installing GlazeWM, the system tray and network on the Windows taskbar disappeared. I want to close the GlazeWM tray, use the taskbar that comes with Windows 11, and only use the tiling function of GlazeWM.
![PixPin_2024-02-15_23-47-53](https://github.com/glzr-io/glazewm/assets/75354658/8f6b095f-9725-4894-b565-a60ec6242876)

**Comment by lars-berger** [comment]
Fixed in v3 👍 [Latest release](https://github.com/glzr-io/glazewm/releases)
