### ISSUE TITLE
Git Bash Resizes on move

### ISSUE THREAD

**Issue by jbm950** [glzr-io/glazewm#540]
I'm having an issue where moving a git bash window causes the font to scale up but not actually affect the "font size setting" in the properties itself. Looking at an issue in FancyZones (https://github.com/microsoft/PowerToys/issues/18112) it looks like it might be tied to commands that include using shift cause the window to rescale.

**Comment by lars-berger** [comment]
Closing as I'm unable to reproduce this in the latest version of Git Bash

If you're still experiencing this, try disabling `ZoomFontWithWindow=no` in Git Bash from a suggestion [here](https://github.com/microsoft/PowerToys/issues/3196#issuecomment-635783449)
