### ISSUE TITLE
Does more documentation exist somewhere?

### ISSUE THREAD

**Issue by NireBryce** [glzr-io/glazewm#541]
The codebase has a documentation folder that just has the readme and contributing guidelines.

I thought there just weren't many commands and they were in the README, but then I found https://github.com/glzr-io/glazewm/issues/380#issuecomment-1706636321 (move workspace up/down/left/right) which isn't listed there.

Is there more complete documentation somewhere?  If not, any recommendations on finding what commands exist? 

I'm having difficulty finding where they are laid out in the codebase, but a lot of that is my lack of knowledge in the language.  I see the commands in the command folders, but they don't have the strings in the config as far as I can tell searching with github code search.

**Comment by ParasiteDelta** [comment]
Eh, documentation has always been kinda hit-or-miss for this project, both for the end-user and the developer.

**Comment by NireBryce** [comment]
understood, no worries -- next time I've got time to poke the code, if I figure it out I'll try to get some down.

**Comment by Xdavlar** [comment]
For anyone reading this, and want to find a starting point in the code. A decent place to start is in the [CommandParsingService](https://github.com/glzr-io/glazewm/blob/main/GlazeWM.Domain/UserConfigs/CommandParsingService.cs) in the function `ParseCommand(...)` on line 68:
```C#
        return commandParts[0] switch
        {
          "tiling" => ParseTilingCommand(commandParts, subjectContainer),
          // TODO: "layout <LAYOUT>" commands are deprecated. Remove in next major release.
          "layout" => ParseLayoutCommand(commandParts, subjectContainer),
          "focus" => ParseFocusCommand(commandParts),
          "move" => ParseMoveCommand(commandParts, subjectContainer),
          "resize" => ParseResizeCommand(commandParts, subjectContainer),
          "set" => ParseSetCommand(commandParts, subjectContainer),
          "toggle" => ParseToggleCommand(commandParts, subjectContainer),
          "exit" => ParseExitCommand(commandParts),
          "close" => subjectContainer is Window
            ? new CloseWindowCommand(subjectContainer as Window)
            : new NoopCommand(),
          "reload" => ParseReloadCommand(commandParts),
          "exec" => new ExecProcessCommand(
            ExtractProcessName(string.Join(" ", commandParts[1..])),
            ExtractProcessArgs(string.Join(" ", commandParts[1..]))
          ),
          "ignore" => subjectContainer is Window
            ? new IgnoreWindowCommand(subjectContainer as Window)
            : new NoopCommand(),
          "binding" => ParseBindingCommand(commandParts),
          _ => throw new ArgumentException(null, nameof(commandString)),
        };
```
From here it is pretty easy to figure out what commands are possible with different arguments.

**Comment by lars-berger** [comment]
The missing commands, like moving workspaces, have been added to a cheatsheet [here](https://github.com/glzr-io/glazewm?tab=readme-ov-file#default-keybindings) now. There's still a lot of improvements that could be made to docs but at least this is resolved now
