### ISSUE TITLE
My cursor don't follow focus

### ISSUE THREAD

**Issue by Rafoshi** [glzr-io/glazewm#542]
This is my configuration file

![image](https://github.com/glzr-io/glazewm/assets/58670715/b2175f61-e84c-4bd3-8144-924b1d99e76b)

**Comment by Lol-Lap** [comment]
> This is my configuration file
> 
> ![image](https://private-user-images.githubusercontent.com/58670715/306482247-b2175f61-e84c-4bd3-8144-924b1d99e76b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1NjU2NjQsIm5iZiI6MTcwODU2NTM2NCwicGF0aCI6Ii81ODY3MDcxNS8zMDY0ODIyNDctYjIxNzVmNjEtZTg0Yy00YmQzLTgxNDQtOTI0YjFkOTllNzZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIyVDAxMjkyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiNTlkMGU2OTdmNGFkN2FmOWI5NWFiYzAzODBlNmM4M2RmNmU4ZGFkMjUyNTY5M2I1ZTllMTdlYTcxMTM3YTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ACIrwsxiE-3im1PK4ciI2MXvlZcJcwOj3mJeAKr-UHo)

it's a typo `cursor_follows_focus`

**Comment by Rafoshi** [comment]
Thank you so much!

**Comment by Lol-Lap** [comment]
> Thank you so much!

Pleasure, make sure you're on the latest version as well.
