### ISSUE TITLE
GPU Percentage reports -1

### ISSUE THREAD

**Issue by Crazzzme** [glzr-io/glazewm#544]
When using the GPU component in the top bar It always reports as -1%. Is there a service or addon I need to use this?

![image](https://github.com/glzr-io/glazewm/assets/719579/3d77b8cc-3202-4ee1-8fc5-52289184ee36)

**Comment by BosEriko** [comment]
I'm experiencing the same thing. It was working fine before but now it's always -1. Did you find a solution @Crazzzme?

**Comment by JesFEREM** [comment]
If you have an nvidia card, what worked for me, update/reinstall your nvidia driver, and open geforce experience. as soon as I opened geforce experience it auto updated GFE and solved the issue.

**Comment by lars-berger** [comment]
I'm closing feature requests and bugs about the built-in bar since it's now been swapped out for [Zebar](https://github.com/glzr-io/zebar). If Zebar doesn't fix what you need, a new issue for it can be opened over [here](https://github.com/glzr-io/zebar/issues)
