### ISSUE TITLE
Regex for Outlook not working?

### ISSUE THREAD

**Issue by franroa** [glzr-io/glazewm#547]
Hi there, I am trying to create a regex for outlook, and I dont manage to do it. 
Does anyone know what I am doing wrong?

```
  - command: "move to workspace 7"
    match_process_name: "/.*Outlook.*/"
```

**Comment by b1scu1t** [comment]
Which version of Outlook are you using? 
This should work for Outlook 2016.
```
-command: "move to workspace 7"
 match_process_name: "OUTLOOK"
```

**Comment by franroa** [comment]
THanks for replying
Sadly not working for me. I am using the last outlook (the so called "Outlook (new)"), its last build is from this 2024

**Comment by FirthR5** [comment]
> Found it: the process is called "olk"

How did you find out the name of the process?
