### ISSUE TITLE
Issue launching WindowsTerminal instead of CMD using `exec`

### ISSUE THREAD

**Issue by JustBarnt** [glzr-io/glazewm#549]
In the config I changed `Alt+Enter` to open WindowsTerminal but it just sits and acts like it opens it an then it does nothing. It like the program just closes instantly.

Not sure if I am doing anything wrong here but if I am I would love some direction.

Thanks!

```yaml
  - command: "exec wt"
    binding: "Alt+Enter"
```

**Comment by lars-berger** [comment]
Unable to reproduce this in the latest version - `shell-exec wt` is working fine 👌 (`exec` was renamed to `shell-exec` in v3) If you're still encountering issues with this, open a support thread on the [discord](https://discord.gg/ud6z3qjRvM) cause it's likely to be environment-related
