### ISSUE TITLE
issue: GlazeWM and QuickAccents

### ISSUE THREAD

**Issue by jaymorelli96** [glzr-io/glazewm#550]
I notice that when using the powertoys QuickAccents with GlazeWM, the quick accents doesn't work as expected. Not sure if this should be fixed in Glaze or in powertoys, but I thought it would be useful to report.

I can still access the letter board using escape, but when I select the letter when using GlazeWM it is not inserted.

**Comment by RaulMeloni** [comment]
Win10 here, latest version. Seems like QuickAccent summons a permanent hidden window (that is summoned again when you activate it), which Glaze catches and somewhat tries to resize. Setting an ignore on its process does not seem to have an effect, but it's possible I'm doing that one wrong.

**Comment by RaulMeloni** [comment]
Update: I wasn't saving my config file properly, I'm dumb. just add 

- command: "ignore"
    match_process_name: "PowerToys.PowerAccent"
    
 under the window_rules section, save config file, make glaze reload it, and change QuickAccent input delay to 100ms or something similar to make it smooth

**Comment by jaymorelli96** [comment]
Perfect! Thanks @RaulMeloni it works perfectly now!

**Comment by lars-berger** [comment]
Added a window rule for this to the sample config v3 👍  [Latest release](https://github.com/glzr-io/glazewm/releases)

```yaml
window_rules:
  - commands: ['ignore']
    match:
      - window_process: { equals: 'PowerToys.PowerAccent' }
```
