### ISSUE TITLE
[Feature Request] Persist pinned tray icons, and collapse tray on start

### ISSUE THREAD

**Issue by 00-kat** [glzr-io/glazewm#551]
Currently, every time GlazeWM is opened, I have to manually alt+click the icons I want pinned.

The tray also always starts expanded, with no option to start collapsed (unless this is an undocumented feature).

**Comment by darianmorat** [comment]
This +1

**Comment by lars-berger** [comment]
I'm closing feature requests and bugs about the built-in bar since it's now been swapped out for [Zebar](https://github.com/glzr-io/zebar). If Zebar doesn't fix what you need, a new issue for it can be opened over [here](https://github.com/glzr-io/zebar/issues)
