### ISSUE TITLE
The icon in system tray disappears

### ISSUE THREAD

**Issue by supengchuan** [glzr-io/glazewm#558]
When the software receives a message, the icon in the system tray will blink. When the icon blnks, its position on the system tray will disappear, causing the entire system tray to fluctuate

I don't think the icon should be lost in its position on the system tray when it is flashing, and the length of the entire system tray should not change

![image](https://github.com/glzr-io/glazewm/assets/18416902/889bd61b-e93f-4c10-a41e-04d8058000b4)

As shown above, it has 14 icons, and at all times it should have 14 icon positions until I quit a certain software

**Comment by lars-berger** [comment]
I'm closing feature requests and bugs about the built-in bar since it's now been swapped out for [Zebar](https://github.com/glzr-io/zebar). If Zebar doesn't fix what you need, a new issue for it can be opened over [here](https://github.com/glzr-io/zebar/issues)
