### ISSUE TITLE
can't use command `move to workspace` in ipc

### ISSUE THREAD

**Issue by DreamMaoMao** [glzr-io/glazewm#559]
```json
{'clientMessage': 'command "move to workspace 4"', 'success': False, 'messageType': 'client_response', 'data': None, 'er
ror': 'Object reference not set to an instance of an object.'}
```

i try to use ipc to Customize something，some command like `workspaces` `focus workspace` work fine.  but the command `move to workspace` doesn't work.

**Comment by lars-berger** [comment]
Fixed in v3 👍 [Latest release](https://github.com/glzr-io/glazewm/releases)
