### ISSUE TITLE
Bug: Hyper-v Manager does not integrate well with Glaze

### ISSUE THREAD

**Issue by vikingnope** [glzr-io/glazewm#562]
Hi,

Just found an issue while running the Hyper-V Manager where the window is not placed next to my other windows like usual, just stays as a normal kind of pop up in the middle:

![image](https://github.com/glzr-io/glazewm/assets/81376423/71013b3a-aa74-4d49-830b-522982a3e12b)

**Comment by lars-berger** [comment]
Elevated windows (ie. run as administrator) cannot normally be moved by the Windows API. The way around it is to run the WM as admin (would not recommended though) or to ignore the window via window rules

Eventually we'll have support for managing elevated windows by having the app signed, but it's a time consuming feature (https://github.com/glzr-io/glazewm/issues/32)
