### ISSUE TITLE
[Feature request] Current language bar component

### ISSUE THREAD

**Issue by volard** [glzr-io/glazewm#566]
It would be cool to have such widget. For now I don't have time to contribute this, so maybe someone before I've got free time will do that.

**Comment by lars-berger** [comment]
Closing feature requests and bugs about the built-in bar since it's now been swapped out for [Zebar](https://github.com/glzr-io/zebar). If Zebar doesn't fix what you need, a new issue for it can be opened over [here](https://github.com/glzr-io/zebar/issues)
