### ISSUE TITLE
[Feature Request] Force bind tiling direction

### ISSUE THREAD

**Issue by Crackpotpower56** [glzr-io/glazewm#568]
Would be nice to be able to force the tiling direction on certain workspaces and/or monitors.

Use case Having Horizontal and Vertical monitors.

I would always like my Vertical monitor to be vertically tiled and my Horizontal to be Horizontally tiled.

**Comment by lars-berger** [comment]
For monitors taller than they are wide, its workspaces will have a vertical tiling direction by default. LMK if this isn't behaving correctly and we can reopen the issue
