### ISSUE TITLE
set width auto increases if i click floating/ignored application

### ISSUE THREAD

**Issue by nahid6970** [glzr-io/glazewm#576]
- command: "set width 520px"
    match_process_name: "rssguard"

here i  have set a particular width for rssguard  when i open it with another app it looks okay but when i open another application where the rules are ignored or floating for those application (qbittorrent), the width of rssguard auto increases !! is there any wa to make it so it doesn't increase the width?

here is the rules for qbittorrent
    - command: "ignore"
      match_process_name: "qbittorrent"
      
      

https://github.com/glzr-io/glazewm/assets/93816648/e8994061-8d5c-4d8d-94ea-b26225fa2d03

**Comment by lars-berger** [comment]
This is fixed in v3 👍 [Latest release](https://github.com/glzr-io/glazewm/releases)
