### ISSUE TITLE
Start menu opens when hitting Windows + R or any other Windows key combination that opens a window

### ISSUE THREAD

**Issue by intercepted16** [glzr-io/glazewm#589]
As the title implies, when pressing any Windows + (_x_ key) combination that opens a window, the start menu also opens, which appears to be related to GlazeWM.

**Comment by JaafarHammoud** [comment]
I have the same problem

**Comment by aaronedev** [comment]
+1 same issue here

**Comment by lars-berger** [comment]
Fixed in v3 🎉 [Latest release](https://github.com/glzr-io/glazewm/releases)

**Comment by ChichiMsdk** [comment]
Seems like it still is an issue on 3.1.1

**Comment by mpriem** [comment]
+1 same issue. would be great to get winkey to work without triggering start menu as ALT is used in so many other programs as a key binding.

**Comment by kola-web** [comment]
v3.8.1 It's still there

**Comment by jgonsior** [comment]
It is still existent, any updates?
