### ISSUE TITLE
Improved Battery Status

### ISSUE THREAD

**Issue by ksaxena149** [glzr-io/glazewm#597]
Right now, the battery component only has three configuration options for draining, power saving, and charging. It would be nice to have more icons similar to how windows does it. Like having different icons for different battery levels like high, medium, low, very low, etc. Can this issue be assigned to me, so I can implement it?

**Comment by Ik549** [comment]
https://github.com/glzr-io/glazewm/pull/402 check this out maybe

**Comment by lars-berger** [comment]
Closing feature requests and bugs about the built-in bar since it's now been swapped out for [Zebar](https://github.com/glzr-io/zebar). If Zebar doesn't fix what you need, a new issue for it can be opened over [here](https://github.com/glzr-io/zebar/issues)
