### ISSUE TITLE
[Feature Request] Open Apps in the Same Monitor as the Mouse Cursor

### ISSUE THREAD

**Issue by Apozzi** [glzr-io/glazewm#599]
It would be awesome if Glazewm could automatically determine the monitor/workspace where the mouse cursor is located when opening applications and open them there.  This would make managing multiple monitors much better.
Always bother me when this app decides to open in another monitor or workspace, alot.

Thanks.

**Comment by GabrielMotaZ** [comment]
Hi!
If you set the config "focus_follows_cursor" on "general" to true it will always open the new app at the right side of the app your cursor is in.

**Comment by lars-berger** [comment]
In order to tile windows, they are opened directionally based off which window has currently focus. @GabrielMotaZ's suggestion could help get the behavior you want, or you can try the new `general.cursor_jump` option to automatically move the cursor as focus is changed

**Comment by clorl** [comment]
I have the same issue and I'd like to note that `focus_follows_cursor` doesn't work when you want to open a window on an empty workspace, as there is no window to focus, at least from what I've been experiencing.

**Comment by frankfium** [comment]
as @clorl stated above, I found another similar issue. When using a launcher (i.e flow launcher) `focus_follows_cursor` doesn't have the same effect as it does when launching an application from the windows search.
