### ISSUE TITLE
[Feature Request] Disable Full Screen on Internal Windows Programs

### ISSUE THREAD

**Issue by LiteWinOS** [glzr-io/glazewm#608]
Keep them Centered tho

or Create a rule to be take just 80% of the screen

programs such control, explorer located in Windows\   Windows\system32\ folders

Feature Request #2:
make a WinPE version

so it will be smaller
and can restore minimized apps [having taskbar or ...]

ty

**Comment by lars-berger** [comment]
The v3 upgrade made a number of improvements to fullscreen behavior - [latest release](https://github.com/glzr-io/glazewm/releases). Binary size was also reduced significantly from 200ish MB -> 27MB. Reopen if you're still experiencing issues related to this 🙏
