### ISSUE TITLE
[Bug] Ghost window after closing file replacement dialog

### ISSUE THREAD

**Issue by altinsmaili** [glzr-io/glazewm#609]
Issue: When saving a file with the same name as another file of the same type in the same location, you're prompted to confirm replacing the existing file. However, when using GlazeWM, after confirming the save, it creates a blank space as if there's an additional window open, even though there isn't.

Steps to replicate:
1. Save a file with the same name as another file of the same type in the same location.
2. Confirm replacing the existing file.
3. Blank space appears as if there's an extra window open, even though there isn't.

Video demonstration: https://youtu.be/Ji6baBRf8jI

**Comment by ParasiteDelta** [comment]
Ahhhh, you may have just helped me figure out why I kept getting ghost windows. Basically, from what I can tell, the subwindow used to prompt for saving is improperly or unusually disposed of after closing, so GWM keeps the container. Not sure if this would be a browser issue or if this would be worth writing an exception for.

**Comment by altinsmaili** [comment]
This issue also occurs outside of browsers. For example, you can replicate it with MS Paint or any other program that allows you to "Save As." It seems the confirmation prompt is still being recognized as a window. I'm not a coder, but is there a way to ignore these confirmation dialogs so they always float and don't behave like regular windows?

**Comment by s-v-o** [comment]
What configuration are you using?
In the [default configuration](https://github.com/glzr-io/GlazeWM/blob/main/GlazeWM.App/Resources/sample-config.yaml) there should be something like this:

```
# Launches system dialogs as floating by default (eg. File Explorer save/open dialog).
- command: "set floating"
  match_class_name: "#32770"
```

Maybe you could experiment with ignore instead of set floating.

**Comment by altinsmaili** [comment]
I tested it with the default configuration, and the same problem occurs. It's most likely not a configuration issue. This dialog prompt likely isn't treated the same as other dialogs. I also tried setting it to "ignore," as you mentioned, but the problem persists. This happens consistently, and since I save files often for my work, it's quite disruptive. I also used "match_title:" with several variants of "Confirm Save As," but none of them worked.

**Comment by lars-berger** [comment]
Are you still experiencing this @altinsmaili? Haven't been able to reproduce this (testing on a w10 machine currently though)

**Comment by altinsmaili** [comment]
@lars-berger Nope! I tried it immediately when the new version came out, but the issue wasn’t there. I just haven’t updated the issue here yet because I haven’t fully switched to version 3. Since you’re not experiencing the issue either, it seems to be resolved. It was really irritating, so thank you so much!

P.S. I'm still on the older version of GlazeWM because I haven't found time to redo all my settings in the new version 😄. I also encountered a problem where the "match process" feature wasn’t recognizing some software, even though the older version did. I’m not sure if it’s something I’m doing wrong or if it’s a new issue. I’ll test it out over the weekend probably and will report it if it's not user error.

**Comment by lars-berger** [comment]
Ay sweet @altinsmaili, will close this one out then

Haven't personally encountered any differences matching on the process name, but it's definitely possible there's a discrepancy there. We previously used a c# exclusive API - [`Process.ProcessName`](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.process.processname?view=net-8.0) (and I'm not 100% sure how it worked under the hood) whereas now we do direct win32 api calls for it.
