### ISSUE TITLE
Unknown key Backspace/BackSpace/backspace

### ISSUE THREAD

**Issue by WantenMN** [glzr-io/glazewm#610]
I want to do this

```
  # Close focused window.
  - command: "close"
    binding: "Alt+BackSpace"
```

**Comment by ParasiteDelta** [comment]
GWM utilizes the Win32 API for keybinds, meaning that you have to use their keycodes for certain keys. There is a link in the README to a keymap, but it's [here](https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.keys?view=windowsdesktop-5.0#fields), and backspace is listed as Back.

**Comment by WantenMN** [comment]
@ParasiteDelta Thank you!

**Comment by ParasiteDelta** [comment]
I would highly suggest joining the Discord server if you require any help like this in the future, as this really isn't the place for similar questions.
