### ISSUE TITLE
Possible to add workspace 0 ?

### ISSUE THREAD

**Issue by keegantoh** [glzr-io/glazewm#613]
Since we only have on our keyboard 0 is just beside 1-9, I am wondering is it possible for workspace 0 as 1 more extra workspace does not hurt as the way I am using is 1 apps per workspace.

**Comment by MoaidHathot** [comment]
@kackburt is correct. You probably also need:
````yaml
  - commands: ["move to workspace 0", "focus workspace 0"]
    bindings: ["Alt+Shift+0"]
```
