### ISSUE TITLE
[Feature Request] Drag window to different monitor moves window to workspace

### ISSUE THREAD

**Issue by nathanautrique** [glzr-io/glazewm#619]
Hi,

First of all, I love the app!

The request: 
Since different monitors have different workspaces, it would be nice if dragging a window from one monitor to another could change it to that workspace. This could also be locked behind a shortcut, for example moving while holding ALT.

Context:
I'm mostly using my keyboard, but for some programs you just really have to use the mouse. 
In those cases it would be nice to keep my hand on the mouse and just drag the windows to another monitors workspace

**Comment by lars-berger** [comment]
This has now been added 🎉 [Latest release](https://github.com/glzr-io/glazewm/releases)
