### ISSUE TITLE
[Feature Request] Move workspace to different monitor with shortcut

### ISSUE THREAD

**Issue by nathanautrique** [glzr-io/glazewm#620]
Request:
Being able to move workspaces across monitors using a **move workspace command**. 
(for example changing _alt + shift + arrows_ to **move workspace** and keeping _alt + shift + hjkl_ as **move window**)

Context:
When waking up from sleep, workspaces get scrambled across monitors. 
My glazewm config binds workspace 9 to monitor 2 and workspace 8 to monitor 3. I make all other workspaces appear on monitor 1.
When going out of sleep mode, workspaces get scrambled across monitors, and I don't have a way to put them back in position. (expect for quiting glazewm and reorganizing everything)

**Comment by apor-tv2** [comment]
Isn't this what Alt + A S D F does in the default config

**Comment by nathanautrique** [comment]
Damn, I missed that, thanks a lot!
