### ISSUE TITLE
windows tray icons not updated

### ISSUE THREAD

**Issue by dinesh-58** [glzr-io/glazewm#621]
When galzewm is started, icons in the windows tray no longer update. For example: in the screenshots below, my laptop was plugged in when starting glaze. *I am using [percentage](https://github.com/soleon/Percentage?tab=readme-ov-file) to show the battery percentage in my tray. The green text indicates charging.*

![windows](https://github.com/glzr-io/glazewm/assets/86787475/6595b654-10d2-4497-8199-61e7579c3f44)

Upon unplugging and using it for a bit, the icons in glaze's statusbar update properly (69% with white text for not charging) but the windows tray stays the same as before (at 70% and charging).

![statusbar](https://github.com/glzr-io/glazewm/assets/86787475/722d0d19-96cc-4dc2-91ec-30dd732a4961)

Not too big of an issue currently since glaze displays the correct icons and I usually have the windows taskbar hidden. But it is a bit jarring when hovering over the windows taskbar and seeing the wrong battery status being reported. Note that this issue occurs regardless if windows taskbar is hidden.

**Comment by lars-berger** [comment]
Closing feature requests and bugs about the built-in bar since it's now been swapped out for [Zebar](https://github.com/glzr-io/zebar). If Zebar doesn't fix what you need, a new issue for it can be opened over [here](https://github.com/glzr-io/zebar/issues)
