### ISSUE TITLE
Process stops working after network disconnect

### ISSUE THREAD

**Issue by xHN7** [glzr-io/glazewm#623]
### Description

When the network disconnects, after a while the GlazeWM process stops working. I need to reconnect to the internet to be able to start it again.

### Steps to Reproduce

1. Run GlazeWM on Windows 10.
2. Disconnect the network.
3. Wait for a while.
4. Observe that the GlazeWM process stops working.

### Expected Behavior

The GlazeWM process should continue to work even when the network is disconnected.

### Environment

- **OS**: Windows 10
- **GlazeWM Version**: (include the version you're using)
- **Additional Details**: (any other relevant information)

**Comment by Ik549** [comment]
it might be the weather component if you've got it in.

**Comment by lars-berger** [comment]
This is no longer an issue in v3 👍 [Latest release](https://github.com/glzr-io/glazewm/releases)
