### ISSUE TITLE
GlazeWM is accessing my Network

### ISSUE THREAD

**Issue by nishan-singh** [glzr-io/glazewm#628]
Hi everyone,

first of all, I wanna thank all the contributors of this great project. I really have been enjoying Glaze for a while now. I don't have any issue with it. I just wanna know, why Glaze is accessing my Network. I had lately no internet and it didn't work well and that's where I inspected my Network Activity and saw Glaze there, but I really don't understand why a Tiling Window Manager has to access my Network? Could anybody tell me the reason. Thanks a lot and if possible, can I manually turn the network access off and Glaze still works fine?

**Comment by aaronedev** [comment]
@nishan-singh most likely due to dev dependencies packages updating etc. Just explore it yourself and then you can verify what actually happens. Furthermore, if you are on windows just disable the outgoing connection with "Windows Defender Firewall with Advanced Security".

**Comment by lars-berger** [comment]
> Hi everyone,
> 
> first of all, I wanna thank all the contributors of this great project. I really have been enjoying Glaze for a while now. I don't have any issue with it. I just wanna know, why Glaze is accessing my Network. I had lately no internet and it didn't work well and that's where I inspected my Network Activity and saw Glaze there, but I really don't understand why a Tiling Window Manager has to access my Network? Could anybody tell me the reason. Thanks a lot and if possible, can I manually turn the network access off and Glaze still works fine?

Are you seeing requests to either `8.8.8.8` or Open Meteo? If so, it's because you either have the weather or network component enabled in your bar config.

**Comment by aaronedev** [comment]
> > Hi everyone,
> > first of all, I wanna thank all the contributors of this great project. I really have been enjoying Glaze for a while now. I don't have any issue with it. I just wanna know, why Glaze is accessing my Network. I had lately no internet and it didn't work well and that's where I inspected my Network Activity and saw Glaze there, but I really don't understand why a Tiling Window Manager has to access my Network? Could anybody tell me the reason. Thanks a lot and if possible, can I manually turn the network access off and Glaze still works fine?
> 
> Are you seeing requests to either `8.8.8.8` or Open Meteo? If so, it's because you either have the weather or network component enabled in your bar config.

word wasn't even thinking about the weather haha

**Comment by nishan-singh** [comment]
@lars-berger Hi, actually, I don't see anything enabled in my config. I just had the standard config that comes with Glaze. Can you tell how to disable the Weather Comp, because I really don't look up for weather everyday xD.

**Comment by aaronedev** [comment]
> @lars-berger Hi, actually, I don't see anything enabled in my config. I just had the standard config that comes with Glaze. Can you tell how to disable the Weather Comp, because I really don't look up for weather everyday xD.

c:\users\"your-username"\glaze-wm\config.yaml <-- open that file and delete the weather widget or comment it out as it says in the instruction.

**Comment by HighPriest** [comment]
The application makes no requests to the network, but is still bound to the 0.0.0.0, where it makes no requests, but it is also bound to 127.0.0.1 address space, where it requests some data.   
Blocking this connection seems to not break any functionality. But still, if there is nothing in the configuration which would require using network connectivity, it would be nice to see GlazeWM **NOT BIND** to any network interfaces.  

Edit:  
I've looked into the code and see that InterProcessCommunication service is used to talk between GlazeWM and GlazeWM-Watcher. I understand the separate thread is necessary to handle cleanup, when GlazeWM crashes or is closed forcefully. 

What do you think about an alternative, using [named pipes](https://docs.rs/interprocess/latest/x86_64-pc-windows-msvc/interprocess/os/windows/named_pipe/index.html) here?

**Comment by HighPriest** [comment]
@lars-berger Can we please re-open this issue?  
Looking at the code of Watcher and IPC server, it shouldn't be hard to implement these "named pipes". I might find time to do it 🤗
