### ISSUE TITLE
Does glazewm support the keybing ";"?

### ISSUE THREAD

**Issue by silence19** [glzr-io/glazewm#631]
Can I use the "JKL;" as keybings the same as i3wm?
I tried to put ; in the config.yaml, but it doesn't accept.
```
  - command: "move right"
    bindings: ["Alt+Shift+L"] # , "Alt+Shift+Right"]
```
Will this semicolon be recognized by glazewm in further version?

**Comment by ParasiteDelta** [comment]
Please read the README. There is a link to Microsoft's official keymap in the Keybindings section, which provides all of the underlying keycodes. The first column on the left contains the value that you want to enter into your config to refer to the specific key. 

https://github.com/glzr-io/glazewm?tab=readme-ov-file#keybindings
which leads to
https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.keys?view=windowsdesktop-5.0#fields
which leads to
`OemSemicolon`

More importantly, this is not an issue with GWM and could have been answered from the Discord server as a typical end-user question.

**Comment by silence19** [comment]
Sorry and thanks

**Comment by zkxjzmswkwl** [comment]
In case anyone stumbles across this from search engine results, recent-ish updates have allowed for the use of ;. Notably, use of OemSemicolon won't result in desired functionality nor will it result in errors.
