### ISSUE TITLE
[Bug] Changing from maximized -> fullscreen via `alt+f` causes flickering

### ISSUE THREAD

**Issue by AmineDjeghri** [glzr-io/glazewm#640]
When you maximize a window (using the window button next to the close button) then press ``ALT+F`` , the windows start shaking then crash.

**Comment by monoelh** [comment]
With me it's not shaking, but the margins are screwed (and the app is not crashing).
`max with button -> alt+f (now top margin bad) -> alt+f (now fullscreen again) -> alt+f (now margins are fine)`

Interestingly, this is working correctly for windows explorer.

That being said, other hotkeys are not working for me (e.g. `alt+shift+a/s/d/f`).

**Comment by AmineDjeghri** [comment]
steps to reproduce : 

- open an app (for example bloc-notes)
- click on 'CTRL+F' to make the window in full screen (the window is in full screen but not maximized)
- click on the maximize button of the window
- click on the unmaximize button (the same buttton)


Temporary fix : 
Change maximized to true 

![image](https://github.com/user-attachments/assets/9c61190a-034a-4bb0-95bd-6151f98a4583)

**Comment by AmineDjeghri** [comment]
![Notepad_Prny8GiVi1](https://github.com/user-attachments/assets/1e80ddb6-8efd-4cc7-9e69-8efbec6aaa1a)
