### ISSUE TITLE
[Feature Request] Be able to change tiling direction when moving window via mouse

### ISSUE THREAD

**Issue by malaow3** [glzr-io/glazewm#641]
When arranging windows via mouse (drag and drop) is there a way to arrange in a different orientation than the currently set tiling direction? E.g., If I have 3 windows but the tiling direction is vertical, how could I drag one windows _under_ another? Is there any config changes I need to do in order to achieve that?

**Comment by Heraclito-Q-Saldanha** [comment]
I would also like this feature

**Comment by lars-berger** [comment]
@LucaCoduriV's pr for this is merged now, so this'll be in the next release 👍
