### ISSUE TITLE
general_startup_commands: unexpected argument found

### ISSUE THREAD

**Issue by tris203** [glzr-io/glazewm#642]
![image](https://github.com/user-attachments/assets/210ddb50-4bbc-4b4f-82e9-867562dcd135)

Since the 3.1 release. I am getting this error on launch. is there any more debugging I can do?
This doesn't seem to line up with anything in config so I am not sure where to start

**Comment by lars-berger** [comment]
There's a minor breaking change since the preview build:
`shell-exec` now directly takes the command to run (e.g.` shell-exec --command cmd` -> `shell-exec cmd`).

To update, remove the `--command` flag wherever `shell-exec` is used (or simply delete the `config.yaml` file to get a new updated one)

**Comment by tris203** [comment]
Thank you so much
