### ISSUE TITLE
[Feature Request] Disable the fade animation when switching workspaces

### ISSUE THREAD

**Issue by AfzGit** [glzr-io/glazewm#647]
Currently, the open windows fade away when switching workspaces which is distracting and slows down the workflow. An option to specifically disable this animations would allow users to enjoy the beauty of the new animations without being hindered by the slower workspace switch speed.

**Comment by gtabuada** [comment]
@AfzGit there is a toggle option for that on the tray icon
![image](https://github.com/user-attachments/assets/c520261f-5720-4b0b-a67d-2df6c2e55b05)

**Comment by AfzGit** [comment]
@gtabuada It disables all Animations. I only want to disable the 'switch workspaces' animations because the default animations for opening windows are good. Switching workspaces while keeping animations is sloggish.

**Comment by gtabuada** [comment]
@AfzGit Well noted. Now that I think of it, I have mine disabled for the same reasons but I also lose the closing/minimizing transition/fade effect. Would definitely make a good feature!

**Comment by lars-berger** [comment]
Getting around to closing a while after it's already been added but this is now in the v3.6.0 release 👍 We use a new method called "cloaking" for showing/hiding windows between workspaces, which doesn't have animations.
