### ISSUE TITLE
[Bug] Tray icon "window animations" toggle doesn't show updated enabled state

### ISSUE THREAD

**Issue by ayaOwO** [glzr-io/glazewm#651]
The "window animations" toggle is persistent through reboots of glazeWM
yet whether the toggle is checked or not on restart isn't

How it works currently:

| Action|Toggle state | window animations Disabled/Enabled |
|--------|--------------|------------------------------------------|
| Start glaze|Checked | Enabled|
| Uncheck toggle| Unchecked| Disabled|
| exit glaze and reopen glaze| checked| Disabled|
| Uncheck toggle| Unchecked| Disabled|
|Check toggle| Checked| Enabled|

Expected
| Action|Toggle state | window animations Disabled/Enabled |
|--------|--------------|------------------------------------------|
| Start glaze|Checked | Enabled|
| Uncheck toggle| Unchecked| Disabled|
| exit glaze and reopen glaze| Unchecked| Disabled|
| Check toggle| Checked| Enabled|
| Uncheck toggle| Unchecked| Disabled|

**Comment by lars-berger** [comment]
Fixed in [v3.6.0](https://github.com/glzr-io/glazewm/releases/tag/v3.6.0) 🙌
