### ISSUE TITLE
Why `glazewm-watcher.exe` persists a terminal session open on launch? (v3.1.0)

### ISSUE THREAD

**Issue by gtabuada** [glzr-io/glazewm#657]
Title says it all
I assume that this watcher is used internally for Glaze to work properly (it is not documented yet).
However I believe it is far from ideal that it spins and persists a whole terminal session on Glaze launch, specially for those who boot it with the system.

* Is it possible to config it out of starting this session?
* If not, is it possible to make it CLOSE this session after it does whatever it has to do?

Having to manually close it all that time, while trivial, is an eyesore.

**Comment by lars-berger** [comment]
Fixed in the [latest release](https://github.com/glzr-io/glazewm/releases) 👍
