### ISSUE TITLE
Multiple monitors - Zebar displaying wrong workspaces

### ISSUE THREAD

**Issue by thomasrayner** [glzr-io/glazewm#659]
I have three monitors. On my left and center monitors, Zebar correctly displays which workspaces are on that monitor. On my right monitor, Zebar displays the workspaces that are on the center monitor, including which is active. The actual functionality works correctly - I can put workspaces on the right monitor and switch between them and workspaces on other monitors properly. But Zebar displays the wrong workspaces.

Edit: My assumption is that this is an issue with the GlazeWM provider, not Zebar itself, so I created this issue here.

**Comment by thomasrayner** [comment]
Now I have one workspace that still behaves correctly in the app but isn't shown on the Zebar bar on any monitor at all. My initial issue also remains.

**Comment by thomasrayner** [comment]
Killing the Zebar process and launching it from the same `.bat` file that GlazeWM calls on startup fixed this issue. Using the system tray icon to exit Zebar and the Start Menu shortcut to launch it did not.

**Comment by thomasrayner** [comment]
Zebar has to be killed and restarted with the `.bat` file every time Windows goes into sleep mode and comes back out, but the other widgets are fine except for GlazeWM.

**Comment by lars-berger** [comment]
Could you open a zebar issue for this @thomasrayner? The `glazewm` provider is fully contained within that repo

As a (hacky) workaround, we could modify the keybinding for reloading the config file to:
```yaml
keybindings:
  # Re-evaluate configuration file.
  - commands:
      [
        'wm-reload-config',
        'shell-exec taskkill -IM zebar.exe -F',
        'shell-exec %userprofile%/.glzr/zebar/start.bat',
      ]
    bindings: ['alt+shift+r']
```
