### ISSUE TITLE
Windows Defender - Trojan Detected (v3.1.1)

### ISSUE THREAD

**Issue by Prajwal-Prathiksh** [glzr-io/glazewm#667]
HI, I'm trying to install the latest version of GlazeWM, but Windows Defender automatically removes the file with the following message.

```
Detected: Trojan:Win32/Wacatac.B!ml
Status: Removed
A threat or app was removed from this device.
Date: 10-08-2024, Sat 08:44
Details: This program is dangerous and executes commands from an attacker.
```

**Comment by lars-berger** [comment]
Recently bought a certificate and setup EV signing to address these virus warnings. The number of reports about virus warnings has improved a lot but there'll still be false positives like this every once in a while. Can't do much else than wait - it takes time and people actively downloading the software to build up more trust with Windows Defender
