### ISSUE TITLE
[Bug] When using glazewm I randomly, but frequently, get my clipboard pasted into windows.

### ISSUE THREAD

**Issue by riskydissonance** [glzr-io/glazewm#674]
### Describe the bug

When using glazewm I randomly, but frequently, get my clipboard pasted into windows.

When switching between windows I find that the window now has clipboard content pasted into it.
I never 'see' the content being pasted, I just find it places, so not sure if it is on defocus or similar.

The paste appears in all manner of applications, it is not limited to one application or workspace.

Closing glazewm causes the issue to stop.

I am using PowerToys as well, should that be relevant.

### Reproduction

On Win 11 23H2, use glazewm.

### Version number

v3.1.1

**Comment by stianeklund** [comment]
I had this same issue on Windows 10. The issue disappeared after I updated to Glaze 3.1, I might have also updated PowerToys, (now on version v0.83.0).

For reference I have Advanced Paste turned off, perhaps that was causing the conflict.

**Comment by riskydissonance** [comment]
Confirm this appears to have fixed the issue, thanks!

**Comment by stianeklund** [comment]
@riskydissonance Consider closing the issue if you can; I don't know if it's worth fixing this kind of issue or not. Perhaps that's up to the maintainer or owner to decide though.

**Comment by riskydissonance** [comment]
I had considered it but there is still a bug when you have the two running together, and thought this was useful to keep open for anyone else who encountered the issue. 

The maintainers can always close it if they feel strongly! 

Thanks for the suggestion though!

**Comment by lars-berger** [comment]
In the latest v3.3.0 release, there's been improvements to how focus is changed between windows. This should be fixed now 👍
