### ISSUE TITLE
Make specific rules to always ignore certain Applications-Programs when launched to only, floating state..

### ISSUE THREAD

**Issue by ComputerCulture** [glzr-io/glazewm#681]
### Describe the problem/motivation

Hello
Enjoying the new version 3 of GlazeWM. If I may ask some question, please.
How can I add certain programs to ignore tiling when launched, and always open in a floating state.  As example Microsoft Outlook. Its ok when full screen but next to another window it hides some of the UI on small monitors, and when you open a new mail window its reduced again.
I know I can toggle the floating state with ALT+Shift+Space, but it would be good to have a rule I can create in the configuration to always open in floating state for this application and other apps I might want to also apply to.
1.	All I need please is an example to show how I can add this to the conf file. I have seen in the config file as example
window_rules: 
# Ignore rules for various 3rd-party apps.
      - window_process: { equals: 'PowerToys.PowerAccent' }
      - window_process: { equals: 'Lively' }
        window_class: { regex: 'HwndWrapper*' }

### Describe the solution you'd like

How can I create one for Microsoft Outlook?  To always open in a floating state. 
I can then applied the same to other apps as well.
Thank you to anyone that can help and get me started with this.

**Comment by lars-berger** [comment]
You can use a window rule with the `set-floating` command to always float a specific window, eg
```yaml
  - commands: ['set-floating']
    match:
      - window_process: { equals: '<PROCESS NAME OF OUTLOOK>' }
```
