### ISSUE TITLE
customizing border radius

### ISSUE THREAD

**Issue by VikramNaik26** [glzr-io/glazewm#686]
### Describe the problem/motivation

As of now i could only change the border colors
Is there any way to change the border radius, if not please add a customization property

### Describe the solution you'd like

similar to border color property add a property for border radius

**Comment by lars-berger** [comment]
I'm closing feature requests and bugs about the built-in bar since it's now been swapped out for [Zebar](https://github.com/glzr-io/zebar). If Zebar doesn't fix what you need, a new issue for it can be opened over [here](https://github.com/glzr-io/zebar/issues)
