### ISSUE TITLE
[Bug] GlazeWM won't start if a custom configuration path is provided

### ISSUE THREAD

**Issue by MoaidHathot** [glzr-io/glazewm#688]
### Describe the bug

If a custom configuration path is provided, GlazeWM crashes immediately.

### Reproduction

Start GlazeWM via `glazewm --config="<custom path to the config.yaml file>"`

### Stack trace or error logs (if applicable)
Couldn't find any error logs

### Version number

3.1.1

**Comment by MoaidHathot** [comment]
I figured it out, it should be `glazewm start --config="<custom path to the config.yaml files>"`

**Comment by lars-berger** [comment]
Thanks for taking care of this 🙏
