### ISSUE TITLE
[Feature Request] Specify config file with an env variable

### ISSUE THREAD

**Issue by nikitarevenco** [glzr-io/glazewm#689]
### Describe the problem/motivation

All other apps i use allow me to customize the location of the config file, it's nice having all logic (so location for "where should config files be located") in a single place 

### Describe the solution you'd like

If `GLAZEWM_CONFIG_FILE` env variable is set, use that as the config file.

**Comment by MoaidHathot** [comment]
Yeah, that would be nice. Currently you can customize the location of the config file via `--config=<path>`
