### ISSUE TITLE
[Bug] Causes 'Edit' dialog to appear in xEdit

### ISSUE THREAD

**Issue by nettoneko** [glzr-io/glazewm#700]
### Describe the bug

Trying to view or edit _any_ field in xEdit while GlazeWM is running causes the xEdit to infinitely ask you to edit that value, reopening the dialog regardless of which option you choose.
The program behaves 100% normally when run without GlazeWM.

https://github.com/user-attachments/assets/f0fdb934-79b0-4530-8bd7-fc9114bcba2b

### Reproduction

- with GlazeWM running, open xEdit
- attempt to edit or view any data field
- now you are in limbo
- close xEdit with Task Manager

### Version number

3.1.1.0

**Comment by lars-berger** [comment]
The Windows API normally doesn't let 3rd-party processes to set focus to a window, so we have to workaround that by simulating a keypress via `SendInput` with a null key. This is normally a no-op for the absolute majority of apps but it seems like this triggers some behavior in xEdit

We recently enabled a special privilege that enables GlazeWM to set focus directly without the fake keypress. There's a build [here](https://github.com/glzr-io/glazewm/actions/runs/10346590163/artifacts/1800397180) that's being tested without the keypress - could you see if this fixes the behavior in xEdit? Didn't bump the version so you might need to uninstall your existing GlazeWM

**Comment by nettoneko** [comment]
The linked build does indeed fix the issue, as well as preventing the Start menu from popping up while using LWin as my modifier. Amazing, thanks!
