### ISSUE TITLE
[Bug] NVIDIA Geforce NOW and KeePassXC should be managed

### ISSUE THREAD

**Issue by proJM-Coding** [glzr-io/glazewm#701]
### Describe the bug

I noticed that with KeePassXC and NVIDIA GeForce NOW they both have a problem which their window behavior isn't controlled by glazewm. Switching focus never selects these windows, these windows spawn as floating even though I have set windows to tiling. These windows show on every workspace and this was not an issue for KeePassXC before the rust rewrite (NVIDIA GeForce NOW always had this issue). I am using mostly the default config, most of my changes are hotkeys. 

### Reproduction

Open ether KeePassXC or NVIDIA GeForce NOW and notice how they both will spawn as floating. Move to any workspace and notice how the window is always shown in every workspace.  Change focus with alt + arrow keys and notice how the focus will never land on ether window.

### Version number

v3.1.1

**Comment by lars-berger** [comment]
When a window is shown on all workspaces like that, it means that GlazeWM isn't managing the window

The logic for whether a window should be managed has mostly stayed the same. One slight difference is that if we fail to get the process name or class name of a window, the behavior now is that we skip managing it - perhaps this is what's happening for NVIDIA Geforce and KeePassXC

**Comment by proJM-Coding** [comment]
That would make sense to me but I don't understand why KeePassXC is not managed after the rust rewrite. Is there some way I can check if it got the process name or class name of a window?

**Comment by Sh00Fly** [comment]
I'm observing the same behavior here.
Here is what Window Spy thinks of KeePassXC window:
![image](https://github.com/user-attachments/assets/a44d98b2-e828-4a4a-b5b1-a075430d59ca)

**Comment by lars-berger** [comment]
> I'm observing the same behavior here. Here is what Window Spy thinks of KeePassXC window: ![image](https://private-user-images.githubusercontent.com/24703597/366234085-a44d98b2-e828-4a4a-b5b1-a075430d59ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwMzk4NzksIm5iZiI6MTcyNjAzOTU3OSwicGF0aCI6Ii8yNDcwMzU5Ny8zNjYyMzQwODUtYTQ0ZDk4YjItZTgyOC00YTRhLWI1YjEtYTA3NTQzMGQ1OWNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTExVDA3MjYxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxZGNlZDQyZWE1NzU4OWQwMzZkYmFmMzYxZTc5ZTVlNjZhYTE2OTM2NzJiYWZkODdlMWNlYjU5MmIyMzcwZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.w0xIl2hlaPWTyfeguUY11ztsTzPQfq_TN4ZCzP7Ewlk)

Hmm the window title, class, and process all look valid in that pic. Does KeePass get managed if you start GlazeWM when the KeePass window is already open?

**Comment by proJM-Coding** [comment]
NVIDIA GeForce NOW does get put in the tiling layout but is still shown on all workspaces. KeePassXC still isn't managed.

Here is winspy for KeePassXC:
![image](https://github.com/user-attachments/assets/6cc5c0c1-ddf5-4335-9fc2-5f4f6012443d)

And here is winspy for NVIDIA GeForce NOW:
![image](https://github.com/user-attachments/assets/2a294b85-8182-4954-ab4e-7a49bac4a603)

**Comment by proJM-Coding** [comment]
Thanks for that, I'll test if it works once the next release is out.

**Comment by proJM-Coding** [comment]
KeePassXC is now managed after installing 3.3.0 but NVIDIA Geforce NOW is still not managed. This was a problem back before with the C# version though.

**Comment by Likver** [comment]
i remember yesterday i opened up gfn and saw that the window was being managed (because it was following all windows rules i had for every window except for those i was ignoring in the ``config.yaml``, and switching workspaces on the same monitor would actually hide the gfn window) but i didnt look at why did that suddenly worked, since i didnt change anything that day as far as i remember, i cant exactly remember if it was after or before updating to v3.5.0, but seeing the discord announcement time when it was posted, id say it was before, so if it was, i dont know why it suddenly managed its window

but today it stopped being managed as usual, while again, i didnt change anything before opening gfn today, so i dont really know what or why did it happen
