### ISSUE TITLE
[Feature Request] Please add an option in the GlazeWM config.yaml file

### ISSUE THREAD

**Issue by ComputerCulture** [glzr-io/glazewm#704]
### Describe the problem/motivation

@lars-berger  Hi, when maximizing a floating Window or a tiling Window to full screen, 
it wont cover up Zebar

Set true or false

Example: In windows OS when you maximize a window to full screen, it wont cover up the Taskbar.

### Describe the solution you'd like

So hoping please this can be done, to have the same effect.

Thank you for a great project

**Comment by lars-berger** [comment]
This can be fixed if we register Zebar as an "app bar" with the Windows API (similar to how the native start menu doesn't get covered on maximize)

There's an open issue for this in the Zebar repo [here](https://github.com/glzr-io/zebar/issues/68)

**Comment by d029940** [comment]
As of v3.1.1 in conjunction with GlazeWM, zebar is still covered in GlazeWM v3.9.1 window is full-screen. Even, when I use the maximum button of the focused window.
