### ISSUE TITLE
[Bug] GlazeWM Loses Sight Of Window When Other Program Interacts With Said Window (Groupy 2)

### ISSUE THREAD

**Issue by Graybooked** [glzr-io/glazewm#706]
### Describe the bug

The program groupy, now Groupy 2 on Steam, lets me turn all programs into tabs I can swap between.

I was hoping to be able to both tile with GlazeWM, and tab with Groupy 2, having some tiles containing tabs each containing programs, and other tiles just having single standard apps.

However, the moment I switch tabs in Groupy 2, both apps in said tabs are 'lost' to GlazeWM, unable to be dragged into a workspace or forcibly alt+shift+1ed etc., with no response to any commands unless I forcibly kill GlazeWM and relaunch it, only for the issue to repeat the moment I switch tabs from one program to another.

This bug of not maintaining sight of a window when interacted with by another program seems like it could reappear for other programs outside of Groupy 2. 

Since this bug forces me to choose between GlazeWM and Groupy 2, since the issue is on GlazeWM's end whereas Groupy 2 continues to function even if windows are tiled by GlazeWM, I am forced to pick Groupy 2 seeing as it is not the program forcing this choice.

### Reproduction

Run a window-containmer program and GlazeWM may lose sight of window; Groupy 2 in my case.

### Stack trace or error logs (if applicable)

```shell
No error logs are generated by this issue.
```

### Version number

Latest

**Comment by lars-berger** [comment]
There's an old issue for groupy support, will close this one so that discussion can be in one place #302
