### ISSUE TITLE
[Feature Request] Workspaces 1 to 9 colors to indicate open apps and no apps open on a workspace...

### ISSUE THREAD

**Issue by ComputerCulture** [glzr-io/glazewm#720]
### Describe the problem/motivation

Hello, Not sure if this has been done or mentioned

Would it be possible for the workspaces 1 to 9 to have colours to indicate 
open apps and no apps open on a workspace
Please see attached image as an example.
![Tiling Panel Bar](https://github.com/user-attachments/assets/2bef2dee-e7bc-4e6c-b635-27a3f30ffff3)

### Describe the solution you'd like

Yes i know in the config file you can
# Optionally prevent workspace from being deactivated when empty.
    keep_alive: true or false

But it would be a nice please to have an option to set to True 
and have different colors as outlined above...
Has anyone added this to there config file?

Thank you

**Comment by aquapaka** [comment]
It would be even nicer if all workspaces could be active/alive from the start, not only after they are selected

**Comment by lars-berger** [comment]
> Would it be possible for the workspaces 1 to 9 to have colours to indicate open apps and no apps open on a workspace Please see attached image as an example. ![Tiling Panel Bar](https://private-user-images.githubusercontent.com/133943765/367494178-2bef2dee-e7bc-4e6c-b635-27a3f30ffff3.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc3ODgyODcsIm5iZiI6MTcyNzc4Nzk4NywicGF0aCI6Ii8xMzM5NDM3NjUvMzY3NDk0MTc4LTJiZWYyZGVlLWU3YmMtNGU2Yy1iNjM1LTI3YTNmMzBmZmZmMy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwMVQxMzA2MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZTNmYmRkOGFkYTljMzljZmVjOGYxZGEyNTkzMjRiZjBmOTkyZDljMmFjOWNiMWRhNjZkM2U0MTE3YmI4NTNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.6_iY_FSMPVuqtkWJ0OR0wqtCloStxewqxE_dZtkxt4k)

You can achieve a style like this by adding a CSS class if the workspace has windows, e.g. modify [this part of the `with-glazewm.html` example in Zebar](https://github.com/glzr-io/zebar/blob/57c558493233846bcd8aaf6ce34b2796df4bb0d2/examples/starter/with-glazewm.html#L134):
```tsx
<button className={workspace.children.length && 'has-windows'}> ... </button>
  ```
