### ISSUE TITLE
[Feature Request] Delete/close workspace

### ISSUE THREAD

**Issue by lohrm-stabl** [glzr-io/glazewm#733]
### Describe the problem/motivation

It happens often, that I have 'ghost' workspaces.
Workspaces which don't have any windows open but they show up in zebar.
It would be nice if there was a way to delete whole workspaces.

### Describe the solution you'd like

A extra command which will close workspaces (and all open windows within).

**Comment by MartianDreamer** [comment]
Do you set 'keep_alive' true for those workspaces? If keep_alive was false, an empty workspaces will be closed. Check it again in your glazewm config file.

**Comment by lohrm-stabl** [comment]
I didn't set it, as I basically use the default config (besides some key remappings).
If I read the code correctly, `keep_alive` should be `false` by default - and therefore not functioning as expected.

**Comment by lars-berger** [comment]
The IPC connection between Zebar and GlazeWM would get disconnected after standby, which has been fixed now in v2.2.1 of Zebar 👍
