### ISSUE TITLE
[Feature Request] Implement toggle workspaces

### ISSUE THREAD

**Issue by Dynge** [glzr-io/glazewm#741]
### Describe the problem/motivation

The feature is inspired from awesomewms [viewtoggle](https://awesomewm.org/doc/api/classes/tag.html#awful.tag.viewtoggle) function.

It is very useful to temporarely join applications from workspaces into a single view.

### Describe the solution you'd like

I imagine an ability to make a keymap such that one can join the toggled workspaces with the current workspace. This should result in all applications om those workspaces to be tiled into view.

**Comment by lars-berger** [comment]
Not super familiar with awesomewm - do tags work the same as workspaces?

**Comment by Dynge** [comment]
I am new to AwesomeWM so i may be wrong, but yes. Tags are the wording they use for workspaces and applications in a workspace is called 'clients'.

I found the feature amazing for the usecase that i want to quickly be able to view windows from different workspaces for a stort duration.

Eg. I find it useful for the following scenario

1. I have the terminal in workspace 1 and a browser in workspace 2.
2. In the browser I open a tutorial for hos to run multiple commands to achieve a task
3. I can toggle workspace 1 and my terminal will now be tiled into view together with my browser.
4. I can now see the tutorial while i type the commands into my terminal. When i am finished I can simply detoggle the workspace 1 (or jump to any workspace, as any toggles will be deselected when switching workspace)

Without toggle i need to move the application back and forth. This becomes even more tedious if there are more windows that i need to complete the task.

Hope it makes sense 😃

**Comment by Dynge** [comment]
Thanks for looking into it <3
