### ISSUE TITLE
Found bug that when glzeWM exits, zebar does not exit with it So I propose a solution.

### ISSUE THREAD

**Issue by Cybecho** [glzr-io/glazewm#747]
### Describe the problem/motivation

- Found bug that when glzeWM exits, zebar does not exit with it

### Describe the solution you'd like

- When glazeWM exits, I want zebar to exit as well.

### Alternatives considered

- Write a batch file so that when glazeWM exits, zebar also exits (including exiting with an exception) 
- Since I don't know how to use rust, I'll leave you with a simple batch file and config file that I tried.

---
# My solution

I added that batch code to the following directory
`%userprofile%/.glzr/glazewm_monitoring.bat`

```
@echo off
:: Check if already running in hidden mode
if "%1"=="hide" goto :hidden

:: Create a VBScript to re-run the batch file in hidden mode
echo Set WshShell = CreateObject("WScript.Shell") > "%~n0.vbs"
echo WshShell.Run chr(34) ^& "%~fnx0" ^& chr(34) ^& " hide", 0 >> "%~n0.vbs"
cscript //nologo "%~n0.vbs"
del "%~n0.vbs"
goto :eof

:hidden
REM GlazeWM process monitoring loop
:loop
tasklist /FI "IMAGENAME eq glazewm.exe" 2>NUL | find /I /N "glazewm.exe">NUL
if "%ERRORLEVEL%"=="0" (
    timeout /T 5 > NUL
    goto loop
)

REM When GlazeWM exits, terminate zebar
taskkill /F /IM zebar.exe /T

```

And I modified the `startup_commands:` in `%userprofile%/.glzr/glazewm/config/yaml` to the following

```
  startup_commands:
    - 'shell-exec zebar'
    - 'shell-exec %userprofile%/.glzr/glazewm_monitoring.bat'
```

---

#### On first run: 
- The script checks to see if it is running in hidden mode, if not, it creates a VBScript to rerun itself in hidden mode.

#### VBScript role:
- Uses a WScript.Shell object to run the batch file in hidden - mode (second argument 0).
- Pass the “hide” argument so that the recursive execution can identify that it is in hidden mode.

#### Re-run batch file:
- Now that the value of “%1” is “hide”, it performs the actual action under the :hidden label.

#### Deleted VBScript:
- Deletes the temporarily created VBScript file after rerunning to ensure that no unnecessary files are left behind.

####   startup_commands:
- Each time glazeWM is run, the batch file will be executed, monitoring the active state of glazeWM

---

See My [repo](https://github.com/Cybecho/Windows_Setting_dotfiles/tree/main/GlazeWM/.glzr).

I hope my crappy alternative contributed to a better glazeWM experience.

**Comment by lars-berger** [comment]
This was just added as a built-in feature in the release a few hours ago 😅There's now a `general.shutdown_commands` option and killing Zebar has been added to the new default config [ref](https://github.com/glzr-io/glazewm/blob/50a9ec0b2c5e4d15871e3a1512ae93087901ef09/resources/assets/sample-config.yaml#L9)
