### ISSUE TITLE
When RDPing to a host running glazewm, open windows vanish

### ISSUE THREAD

**Issue by nascentt** [glzr-io/glazewm#77]
If I RDP to a host that is running glaze. Open windows disappear until I exit glazewm.
I've tested this on single monitor to single monitor connections and multiple monitor connections and it's the same. Until I close glaze I cannot access any windows that were open.

If I disconnect the rdp session the windows are still hidden until I close glaze.

Not a major issue. It just means closing and reopening glaze anytime I RDP onto the computer, but figured I'd put in an issue for it.

**Comment by lars-berger** [comment]
That's a really interesting use case; I would never have thought to troubleshoot this. Unfortunately don't have a Windows Pro license available right now to test RDP, but it's good to have the issue documented for reference.

Been busy with changing jobs and changing jobs the last couple weeks, but will be once again active with the repo soon 👍

**Comment by lars-berger** [comment]
Haven't personally tried it but heard from the discord that RDP'ing is behaving correctly in new versions now. Let me know if this is still an issue and should be re-opened 👍
