### ISSUE TITLE
monocle layout support?

### ISSUE THREAD

**Issue by ut4k** [glzr-io/glazewm#78]
Will this software support monocle layout in the future?
If so, it could be the best wm for windows for me.

**Comment by lars-berger** [comment]
Is monocle layouts a feature from bspwm? 

Looking to add some sort of fullscreen toggle feature in the future, ref [here](https://github.com/lars-berger/GlazeWM/issues/70#issuecomment-1124342503). The implementation is likely to be similar to the `fullscreen enable` command in i3.

**Comment by tgharib** [comment]
> The implementation is likely to be similar to the `fullscreen enable` command in i3.

AFAIK, equivalent of monocle layout in i3 would be `layout tabbed` instead of a simple fullscreen.

**Comment by ericreeves** [comment]
I have no idea what this is called in i3, but ultimately the behavior is:

When monocle mode is enabled, it behaves exactly as if only a single application is open in a workspace, so the application takes up the whole screen (excluding configured gaps), but then you can still use next/prev app to cycle through all apps open on that workspace.  Disabling monocle mode restores windows to their previous locations.

It doesn't use proper "full-screen" or "maximize", so it should be far simpler to implement than #70 .

Thanks for your work on GlazeWM!  Given all of the TWM-like options on Windows, I feel it's the best one so far!

**Comment by b1scu1t** [comment]
I think a nice way to implement this only checking 'managed' (not floating/ignored) windows and minimizing/hiding anything but the focused window. Though...this way GlazeWM would have to remember the window states *before* Monocle is activated.

**Comment by ut4k** [comment]
what i want be like:
[https://i.imgur.com/oVatUvy.png](https://i.imgur.com/oVatUvy.png)

**Comment by freestingo** [comment]
+1 for this layout; it's the one I use pretty much all the time in `xmonad` and would really love to see it also implemented here

**Comment by lars-berger** [comment]
Closing in favor of #678
