### ISSUE TITLE
[Bug] Focus does not move to browser workspace after link is opened.

### ISSUE THREAD

**Issue by rmanthorpe** [glzr-io/glazewm#780]
### Describe the bug

Before v3.4.0, clicking a link in one application would move to the workspace of the browser window it opened in. Now it does not. My browser is Brave.

### Reproduction

- Open a browser in one workspace.
- Open a different application with a link to click in a second workspace.
- Click the link. It will open in the browser but focus will not shift to the workspace with the browser window in it.

### Version number

3.4.0

**Comment by DreamMaoMao** [comment]
In linux, the browser sends an activation request to the window manager, who then decides what to do with the request, but it is not known if the same process is used on windows.

**Comment by DreamMaoMao** [comment]
https://github.com/user-attachments/assets/169d6598-1d39-440e-b5d9-063bd68cc378

I will briefly display the browser, and then black screen...

**Comment by DreamMaoMao** [comment]
https://github.com/user-attachments/assets/67360983-16dc-4522-b5e7-1abfb65c3405

He become normal after I rebooted the system

**Comment by DreamMaoMao** [comment]
Sometimes I succeed and sometimes I fail

**Comment by Line-Noise** [comment]
If this is in fact a bug please don't fix it (or make it optional)! I hate it when something moves my focus.

**Comment by DreamMaoMao** [comment]
> If this is in fact a bug please don't fix it (or make it optional)! I hate it when something moves my focus.
I don't quite understand what you mean, you are based on what kind of scenario would bother you, can you describe the specific scenario

**Comment by DreamMaoMao** [comment]
> If this is in fact a bug please don't fix it (or make it optional)! I hate it when something moves my focus.

I don't quite understand what you mean, you are based on what kind of scenario would bother you, can you describe the specific scenario
