### ISSUE TITLE
[Bug] Gap configuration based on pixel value

### ISSUE THREAD

**Issue by matsavage** [glzr-io/glazewm#781]
### Describe the bug

There should be an option to define gaps based on zebar size/display scaling

Situation:
I have a laptop which I mostly use plugged into 2 4K monitors (125-150% scaling), and set the gaps and bars to be appropriate for the display
When using the laptop on the go, it has a high DPI display and will often be at ca. 250% scaling which causes the following with the top bar:
![image](https://github.com/user-attachments/assets/0fad8a74-7058-4539-9b89-88a9e19f1412)

### Version number

3.3.0

**Comment by lars-berger** [comment]
Didn't get around to closing this one, but we got a fix in for this one in the v3.4.0 release. There's a new `gaps.scale_with_dpi` option to toggle whether gaps should be scaled, which is enabled by default now 👍
