### ISSUE TITLE
[Feature Request] Remember window position

### ISSUE THREAD

**Issue by feraxhp** [glzr-io/glazewm#782]
### Describe the problem/motivation

Allow to glazewm remember the last state of a window.

The problem is, that when you open in full screen as video, or minimize a window, breaks the layout that you have configured before.

### Describe the solution you'd like

I would like to reopen programs, Maxime, etc... and the size of the windows and its position be the same as I was the last time.

### Alternatives considered

- Add a helper to know the class and name of the windows you select
- Add a configuration to set the width, height and position for a window class and name.

**Comment by psarras** [comment]
It sounds very similar to one of my issues. On one workspace I have two apps, where I like them split 2:1 i.e. The first would be twice as long as the second one. I do this manually, and whenever something changes there, I minimize or maximize one of those temporarily, this is lost. It would be great to remember this preferred configuration either automatically, or even better by specifying those two apps on the config and also specifying their order, so which one would be set from left to right. 

A similar request would be to set that preference on the workspace itself. i.e. workspace 2, will have the first app taking up 2/3 of the workspace and the second app the other 1/3. Any additional windows would be dealt as currently.
