### ISSUE TITLE
[Feature Request] "fibonacci" spiral splitting

### ISSUE THREAD

**Issue by jinchoung** [glzr-io/glazewm#794]
### Describe the problem/motivation

i've seen this feature in other window managers and it seems really useful actually. first split splits the windows in half, next split only splits one of the now two windows in half, next split splits only one of the smallers windows, etc.

and each time, the original window retains the larger window and the new window is relegated to the smallest split... this kind of tracks with my focus - "primary, secondary, tertiary, etc" with the laterst window being the least important (although it might be a good idea to make it an option for the reverse - newest window gets the largest space).

### Describe the solution you'd like

instead of splitting the main screen equally between all new windows at every step, the first split results in two equal windows. the next split results in three windows with one window remaining half the monitor and the other half is split into two windows. the next split would only split one of the two smaller windows.... etc.

**Comment by lars-berger** [comment]
Closing in favor of #678
