### ISSUE TITLE
[Bug] `focus_follows_cursor` doesn't work with touchpads

### ISSUE THREAD

**Issue by kurushimee** [glzr-io/glazewm#799]
### Describe the bug

The `focus_follows_cursor` option only works with an external mouse. If moving the cursor by using a touchpad (i.e. a built-in laptop touchpad), this option doesn't work: despite moving the cursor over a different window, the focus doesn't change. If you do the same thing by using a mouse, then the option works correctly and cursor changes window focus.

For clarity, I'm using a Huawei Matebook D15 AMD running Windows 11.

### Reproduction

1. Enable the `focus_follows_cursor` option.
2. Try moving the mouse cursor to another window by using a touchpad.
3. Observe focus staying on the same window, not changing when hovering the cursor over another window.

### Version number

v3.4.0

**Comment by Ajay-056** [comment]
Im facing this issue too, Using HP laptop with windows 11. I wont be using external mouse most of the time, found this when using randomly. It would be very helpful if fixed.

**Comment by proJM-Coding** [comment]
Can confirm this issue is on v3.5.0
I have no errors though and using a mouse does fix it. I only got this issue when updating to v3.5.0 though.

**Comment by kurushimee** [comment]
Sorry, I don't have the ability to confirm it at the moment, but as far as I remember `focus_follows_cursor` never worked for me with a touchpad, so I think it didn't work even after a re-launch of GWM.

**Comment by proJM-Coding** [comment]
> Live-reloading doesn't currently work this feature. Could you confirm that `focus_follows_cursor` still doesn't work after a full re-launch of GWM?

I can confirm that doing a reload, re-launch, reboot and even editing config doesn't fix the issue.

**Comment by HolbyFPV** [comment]
Understood.  If you have no errors in your logs, I would guess the issue is due to this.  
https://github.com/glzr-io/glazewm/blob/382c8a1a26a18b068a796dd05d4ad253b7672826/packages/wm/src/common/platform/event_window.rs#L109
Trackpads may need to be registered in a different way.  `HID_USAGE_GENERIC_POINTER` might be the solution, but I'm unsure how to test this theory since I don't have hardware that reproduces the issue.

**Comment by bruhmomento124** [comment]
I have a device that reproduces this issue, I attempted to modify HID_USAGE_GENERIC_MOUSE to be HID_USAGE_GENERIC_POINTER but the issue still persists when I compile and run, could be an issue with me though, not too familiar with Rust and Windows API stuff.

If there is anything for me to test please let me know. For context I am using a Lenovo L13 Yoga.

**Comment by proJM-Coding** [comment]
I am also using a lenovo device, Thinkpad L14 gen 4.

**Comment by bruhmomento124** [comment]
This line appears to be causing the issue, commenting it out makes focus follows cursor work as expected. Seems to be a fix for a different issue so removing it is not a permanent solution, any idea why this is the case?

https://github.com/glzr-io/glazewm/blob/0f9b562ef66bac6227daeedb5d85690cc08280fd/packages/wm/src/common/platform/event_window.rs#L275
