### ISSUE TITLE
[Bug] moving a tiled window with mouse to any direction changes it's workspace

### ISSUE THREAD

**Issue by AmjadAlwadi** [glzr-io/glazewm#829]
### Describe the bug

when there is a single window in a workspace in tiled mode and there is another workspace open in the background then moving that window with the mouse to any direction causes it to change it's workspace for some reason.

https://github.com/user-attachments/assets/2540f7d6-5fa1-4d77-87a0-78d792a7beae

### Reproduction

open 2 workspaces.
in the first one add one tiled window.
in the second one add 2 horizontal windows above each other.
in the first workspace try to move the window by grabbing it with the mouse to any direction.
now it should change it's workspace to the second one

### Version number

3.4.0

**Comment by DreamMaoMao** [comment]
can't reproduce

**Comment by AmjadAlwadi** [comment]
i updated to the latest version 3.5.0 and the bug still exists but you need 2 windows or more stacked horizontally on the top side and one window on the bottom side, so here are the steps again:
open 2 workspaces.
in the first one add one tiled window.
in the second one add 3 horizontal windows, one at the bottom and 2 at the top stacked horizontally.
in the first workspace try to move the window by grabbing it with the mouse to any direction.
now it should change it's workspace to the second one

**Comment by jorbig** [comment]
The bug is still present in 3.6.0

It actually is even easier to reproduce:
1. Open a tiled window in an empty workspace
2. Move that Window with the mouse.

You can now see that window automatically moved over to the the first workspace.
