### ISSUE TITLE
[Bug] I can't open GlazeWM

### ISSUE THREAD

**Issue by Tsubasu-no-aru-Okami** [glzr-io/glazewm#845]
### Describe the bug

I use this programm for a while with Zebar. Then, I delete Zebar and after that GlazeWM don't open and just say me: "missing field "general"". I have tried to reinstall app or repair, but it doesn't work.

![изображение](https://github.com/user-attachments/assets/7f997be8-0afd-4de7-9c6d-aba6a13f6ef7)

### Version number

3.5.0

**Comment by theBNT** [comment]
why did you delete zebar? do you mean the application or the config as described in the release pages? did you upgrade from a very old version before? i think more information is required, maybe something specific to your config.yaml

**Comment by lars-berger** [comment]
It looks like you've got a wonky config at `%userprofile%\.glzr\glazewm\config.yaml`. If you delete it, GlazeWM will generate a new sample config for you on startup 👍
