### ISSUE TITLE
[Feature Request] Disable tab between multiple workspaces (several monitors)

### ISSUE THREAD

**Issue by dannykentala** [glzr-io/glazewm#848]
### Describe the problem/motivation

I usually have two or more applications in one workspace. But when using tab it switches between the workspaces opened in others monitors

### Describe the solution you'd like

Allow disable tab between workspaces if I have 2+ monitors

Config could be in general section

**Comment by lars-berger** [comment]
This is fixed now in [v3.7.0](https://github.com/glzr-io/glazewm/releases/tag/v3.7.0) 🙌 There's a new config option `general.show_all_in_taskbar` to toggle this behavior (only shows the current workspace windows by default now).
