### ISSUE TITLE
[Feature Request] Configure gaps per-monitor

### ISSUE THREAD

**Issue by anventia** [glzr-io/glazewm#871]
### Describe the problem/motivation

I am using a Windhawk mod that autohides the taskbar when a window intersects it. I would like the option in GlazeWM to change the gaps per-monitor, so I can increase the gap on the bottom of my secondary monitor, thus always showing the taskbar on that monitor only.

### Describe the solution you'd like

Additional config for gaps for multiple monitors

### Alternatives considered

N/A

**Comment by lars-berger** [comment]
Duplicate of #796
