### ISSUE TITLE
Is it possible to have Binary Space Partitioning automated?

### ISSUE THREAD

**Issue by alber70g** [glzr-io/glazewm#879]
I'd like to use BSP as my default for positioning new windows. Preferably with a falloff width. For example, I have a 21:9 screen, so I want to have the binary space only kick in when the width is less than 1/3 of the width. 

> Is it possible to have this automated?
> 
> I think GlazeWM is very solid from my initial hour of using it, but I prefer the BSP style of tiling. I also use Sway, and I use the [autotiling](https://github.com/nwg-piotr/autotiling) script to simulate BSP-like tiling on Sway. Would it be possible to integrate something like the autotiling script to GlazeWM where it toggles between vertical and horizontal per window launch?
> 
> _Originally posted by @JJGadgets in https://github.com/glzr-io/glazewm/issues/37#issuecomment-1180155259_
>

**Comment by lars-berger** [comment]
There's a couple similar scripts for GlazeWM as well for automatically changing the tiling direction - [ParasiteDelta/GlaAlt](https://github.com/ParasiteDelta/GlaAlt) and [burgr033/GlazeWM-autotiling-python](https://github.com/burgr033/GlazeWM-autotiling-python).

There's an open issue for full layout support here #678
