### ISSUE TITLE
[Feature Request] Add auto-tiling to Glaze WM as an option

### ISSUE THREAD

**Issue by ValdamireGido** [glzr-io/glazewm#883]
### Describe the problem/motivation

There are separate community scripts or applications (Like GatAlt or glaze-autotiling mentioned in Readme). It would be nice if such behaviour would exist in GlazeWM itself and can be adjusted by just an option in GlazeWM's config file. 

### Describe the solution you'd like

Have an option to select tiling behaviour including current default one and some auto tiling modes similar to currently existing community solutions.

**Comment by lars-berger** [comment]
Definitely agree that this would be a nice feature 👍 We have an open issue for automated layouts here #678. Will close this one to keep discussions in one place
